### ISSUE TITLE
Incorrect results from polyfill

### ISSUE THREAD

**Issue by usuallycwdillon** [uber/h3#119]
I've been having a conversation with @nrabinowitz on [SO](https://stackoverflow.com/questions/51771684/how-do-i-configure-the-simplefeaturetypebuilder-to-build-center-facing-gnomonic) about unexpected results from `polyfill`. 

I noticed the issue while working in [h3-java](https://pastebin.com/0X63eKE1), but my results are consistent with [h3-py](https://pastebin.com/UvwHuCV8) and[ h3-js](https://pastebin.com/jgAwEMrr). I get similar (looking) results at resolutions 2, 3, and 4.  

Using  the same [GeoJSON input](https://pastebin.com/wH1SgCY8) asking for a `polyfill`, @nrabinowitz gets 282 correct-looking hexes at resolution 3. I get 349 hexes, none of which have the same address as his 282. I [posted a .csv](https://pastebin.com/EEvAhqUa) with his results vs mine.

I've tried installing later versions of H3Core and bumped the initial Java version from 3.0.2 (when I started) to 3.0.4 but I got the same (incorrect) results.

**Comment by isaachier** [comment]
Can you publish the compiler/operating system/CPU architecture you are running on?

**Comment by usuallycwdillon** [comment]
Sure. 
I'm using Suse Tumbleweed, `Linux 4.17.12-1-default #1 SMP PREEMPT Fri Aug 3 06:36:01 UTC 2018 (ef4920c) x86_64 x86_64 x86_64 GNU/Linux`
make is `GNU Make 4.2.1 Built for x86_64-suse-linux-gnu`
gcc is `gcc (SUSE Linux) 8.1.1 20180719 [gcc-8-branch revision 262874]`

**Comment by isaacbrodsky** [comment]
I was able to reproduce this issue using your Java code. I got 349 hexagon IDs, and I see they match some of the addresses you got.

I believe the problem here is that H3 expects coordinates in the latitude,longitude order, but GeoJSON uses longitude,latitude order. When I swap the coordinates, I get 282 hexagon IDs and they match @nrabinowitz' set.

**Comment by isaachier** [comment]
Wow good catch.

**Comment by usuallycwdillon** [comment]
Ah. I'm so glad you recognized that. I had them the correct way in an earlier attempt, but the output was transposed. Everything works perfectly when I deal with it on the output, too. 

Thank you.  I'll close this.

**Comment by guillemfrancisco** [comment]
Have this issue been fixed? In a GeoJSON the coordinates are in the order [lon,lat]. However, the polyfill function expects the coordinates to be [lat,lon]. So we aren't truly following the GeoJSON standards.

**Comment by guillemfrancisco** [comment]
Just saw the issue #141 ! Will move to the python bindings repo! :)

**Comment by nrabinowitz** [comment]
> Have this issue been fixed? In a GeoJSON the coordinates are in the order [lon,lat]. However, the polyfill function expects the coordinates to be [lat,lon]. So we aren't truly following the GeoJSON standards.

The core library doesn't attempt to follow GeoJSON - this is left as a job for the bindings, and in some cases additional libraries, to handle.
