### ISSUE TITLE
polyfill not filling the complete polygon

### ISSUE THREAD

**Issue by nmandery** [uber/h3#136]
Hello,

I just stumbled on an issue where the `polyfill` function is not able to fully fill polygons. The problem  affects long, diagonal polygons, like this:

![bug-r13](https://user-images.githubusercontent.com/140716/44656755-7387d500-a9fa-11e8-8358-29d581d51028.png)

The blue part is the polygon, the green shape are the generated hexagons. Here is a closeup of the lower end of the polygon:

![bug-r13-close](https://user-images.githubusercontent.com/140716/44656804-a205b000-a9fa-11e8-9c62-21d9e1a0c3b9.png)

The `polyfill` was done at resolution 13. Interestingly the result at resolution 12 looks much better:

![bug-r12-close](https://user-images.githubusercontent.com/140716/44656837-d37e7b80-a9fa-11e8-8a3f-d8a482edd7d1.png)

The GeoJSON for my test polygon is

    {"type":"Polygon","coordinates":[[[5.76910652153309,51.1122595579185],[5.74843667987113,51.0844285870957],[5.74868565718131,51.0841156106137],[5.76939661923247,51.1120877871771],[5.76910652153309,51.1122595579185]]]}

To further investigate this issue I went ahead and removed the line of code which does the removal of heaxgons located outside the polygon in this file:

https://github.com/uber/h3/blob/96a0e86d6a80f0d5e83e7a9d1fde34147847af27/src/h3lib/lib/algos.c#L710

I took this approach because I wondered about the clean cut at the end of the filled part  and wanted to see in which radius H3 is generating it indexes.

Running `polyfill` on my test polygon again gave the following results:

Resolution 12:

![hack-r12](https://user-images.githubusercontent.com/140716/44657129-1c82ff80-a9fc-11e8-898a-ee0142050eb7.png)

Resolution 13:

![hack-r13](https://user-images.githubusercontent.com/140716/44657134-23117700-a9fc-11e8-9556-c7aee12aaf6f.png)

So the filled `minK` hex radius seems to be a bit too small for this case. I gave it a try and changed the 1.5 multiplicator in

https://github.com/uber/h3/blob/96a0e86d6a80f0d5e83e7a9d1fde34147847af27/src/h3lib/lib/bbox.c#L120

to the - wildly guessed value - 1.35:

    return (int)ceil(bboxRadiusKm / (1.35 * centerHexRadiusKm));

This value is certainly not mathematically correct and needs to be validated. It also increases the number of indexes being generated, but gave me a polygon completely covered in indexes:

![hack-r13-crude-fix](https://user-images.githubusercontent.com/140716/44657367-dda17980-a9fc-11e8-8bad-029eac83a4bc.png)

So I assume the issue is in the `bboxHexRadius` function in combination with filling shapes with a large number of indexes. This function seems to have some deficits dealing with long, thin, diagonal shapes. 
I did not notice any issues when using `polyfill` with rounder geometries.

**Comment by dfellis** [comment]
Definitely an amazing bug report.

I disagree on leaving the issue alone until h3ToIJ is ready for use, though. I think we should alter the scaling factor to guarantee correctness and deal with the polyfill slowdown for the short term and then get the performance back up.

We don't have to do the math to determine the maximum extent of hex distortion, if that's what you're worried about wasting time on; just set the constant to something we know could never be reached even with distortion, such as 1.1, and move on.

**Comment by nmandery** [comment]
Thank you both!

You are correct @nrabinowitz , resolution 11 also has this problem:

![bug-r11](https://user-images.githubusercontent.com/140716/44704594-32480180-aa9c-11e8-9f44-3c4e347d5e18.png)

I had a brief look at #102 and will keep an eye on this functionality in the future. For now I will wait and use the released version of H3.

In the meantime I am thinking of additionally tackling this issue outside of H3 by splitting the polygon into smaller parts and running `polyfill` on each of them separately. I hope to compensate the increased radius and keep performance up by having to generate and check less indexes.

**Comment by nmandery** [comment]
I just noticed something embarrassing - seems I had a quite stupid bug in my code I simply missed. 

I will re-check this issue tomorrow, but there is a good chance this issue is invalid and H3 works as expected. So please do not spend any more time on this right now.

**Comment by nmandery** [comment]
Please close this issue as invalid. The problem was caused on my side where I had a systematic mixup of coordinate positions (x,y to lon,lat and back). I am working on an Postgresql binding for H3 and the bug happened during the translation from native postgresql geometry types to the H3 types. Because this error was a systematic mistake, it took a while for me to notice it. It can be frustrating when such simple errors can be the cause for bugs.

Thank you both for your support. I am sorry for the effort this caused on your side.

**Comment by nrabinowitz** [comment]
I think it might still be worth looking into this, though - the original bug report seemed legit, and even if the OP's current issue is solved, there may still be areas of the world/H3 resolutions where this is an issue. Seeing if we can get a repro case would allow us to say whether we fixed it with an `h3ToIJ` implementation.

**Comment by nrabinowitz** [comment]
This issue is legitimate, even if it doesn't affect the OP. Reversing the lat/long in the test case is still a valid polygon, and does hit this issue.

Repro case:
```
static GeoCoord testVerts[] = {{0.10068990369902957, 0.8920772174196191},
                               {0.10032914690616246, 0.8915914753447348},
                               {0.10033349237998787, 0.8915860128746426},
                               {0.10069496685903621, 0.8920742194546231}};
static Geofence testGeofence = {.numVerts = 4, .verts = testVerts};
static GeoPolygon testPolygon;

SUITE(polyfill) {

    testPolygon.geofence = testGeofence;
    testPolygon.numHoles = 0;

    TEST(weirdShape) {
        int res = 13;
        int numHexagons = H3_EXPORT(maxPolyfillSize)(&testPolygon, res);
        H3Index* hexagons = calloc(numHexagons, sizeof(H3Index));

        H3_EXPORT(polyfill)(&testPolygon, res, hexagons);
        int actualNumHexagons = countActualHexagons(hexagons, numHexagons);

        printf("Hex count: %d\n", actualNumHexagons);

        free(hexagons);
    }
}
```
Output with the current `1.5` coeffecient in `bboxHexRadius`:
```
TEST polyfill
Hex count: 3945
```
Output with the coefficient set to `1.0`:
```
TEST polyfill
Hex count: 4353
```

**Comment by nrabinowitz** [comment]
@greatathrun There's currently a known issue where you can't polyfill a polygon containing a pole. For this particular purpose, though, you ought to be able to use the `h3ToGeoBoundaryHier` utility, passing in each of the base cells.
