### ISSUE TITLE
h3 polyfill crash

### ISSUE THREAD

**Issue by kiki1992** [uber/h3#153]
when I use polyfill with target coordinates and resolution 8, the java application crashed.
here is the coordinates
119.773625,31.339057;119.391881,31.449531;119.180312,31.433757;118.407626,31.354847;118.232851,31.433757;117.846508,31.622867;117.736124,31.370635;117.276192,31.267969;116.825458,31.030618;116.834657,30.705271;116.521903,30.562084;117.073822,30.546161;116.963438,30.219162;117.119815,29.77075;117.147411,29.3203;117.910899,29.296112;117.920097,29.376717;118.370831,29.762724;119.115922,30.075252;119.769026,30.251113;119.842615,29.818891;120.219759,29.666362;120.652096,30.027236;120.799274,30.41071;120.753281,30.760897;120.587705,30.91965;120.100177,30.895854;119.916204,31.204734
here is the err file
[hs_err_pid23932.log](https://github.com/uber/h3/files/2458546/hs_err_pid23932.log)

**Comment by isaacbrodsky** [comment]
Hi, what version of h3-java are you using? This might be fixed in version 3.1.0.

**Comment by kiki1992** [comment]
thank you, it works fine in version 3.1.0.
