### ISSUE TITLE
Compile to SO

### ISSUE THREAD

**Issue by seanhandley** [uber/h3#161]
Hello,

I'm writing Ruby bindings for h3 and I hit a small roadblock. The compiled library is a `.a` file but the tool I'm using to build the bindings (https://github.com/ffi/ffi) expects a `.so` file.

I manually converted the `.a` file using `ar` and `gcc -shared` but it'd be nice to have an `.so` version installed automatically.

What are your thoughts?

**Comment by dfellis** [comment]
Hey @seanhandley the H3 project already has the `BUILD_STATIC` cmake argument. If you just turn that off, it will build a `.so` file for you, eg `cmake . -DBUILD_STATIC=off && make`.

**Comment by dfellis** [comment]
The H3 library does already support building `.so` files directly, you need to use the command: `cmake . -DBUILD_SHARED_LIBS=true && make h3` to do so.

(I had posted an earlier comment, but that was for an earlier version of H3, hopefully you didn't see that.)

**Comment by seanhandley** [comment]
Ahh perfect. Thanks!
