### ISSUE TITLE
Add h3Line algorithm

### ISSUE THREAD

**Issue by nrabinowitz** [uber/h3#162]
Add a function `h3Line(start, end)` that returns the list of hexagons between the start and end indexes, inclusive.

I'm currently working on this.

**Comment by dfellis** [comment]
Will this be something like [Bresenham's Algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm) or something like [Red Blob Games Hex Line Algorithm](https://www.redblobgames.com/grids/hexagons/#line-drawing)?
