### ISSUE TITLE
Questions about terminology

### ISSUE THREAD

**Issue by fxn** [uber/h3#166]
Hey! I am getting familiar with H3, have watched a couple videos and read the docs, but there are some things that are not totally clear to me. Let me open an issue to clarify them, but please don't hesistate to point me to a mailing list or whatever if that would be better.

To give you context, let me say that I am a mathematician by training (though it's been 20 years!). I understand conceptually the whole idea of H3 with the tessellation of the icosahedron in regular hexagons (mod 12 pentagons per resolution), projection to the sphere, resolution levels, and unique indexing of each element of the union of all the hexagons of all resolution levels.

OK, now we have the concept of a _k_-ring. As I visualize it, given an origin _H_, the 0-ring of _H_ is the set that has _H_ itself as unique member, the 1-ring of _H_ consists of its 0-ring together with the neighbors of _H_ (same resolution level), the 2-ring consists of the 1-ring together with the next circunference of hexagons, etc.

A _k_-ring is a patch, a solid regular/symmetrical shape unless it touches a pentagonal distortion, in which case the ring is still well-defined, only its shape is not regular. That explains why the function `kRing` may contain holes instead of having exactly `maxKringSize` elements, correct?

Is `kRingDistances` like `kRing` plus distances for each hexagon? Do the array of indexes and the array of distances match each other one-to-one, where `out[i]` is at distance `distances[i]` of the origin?

Then, I guess that the _k_-hexRing at origin _H_ consists of the set difference of the _k_ and _k_ – 1 rings at origin _H_ for _k_ > 1, and exactly 0-ring for _k_ = 0. That is, the perimeter of the ring so to speak. Also, hexRings can be discontinuous if they traverse pentagonal distorsions, but in that case they are still defined. Correct?

If I got that right, then, what is a range?

> hexRange produces indexes within k distance of the origin index

How are indexes within _k_ distance of the origin different from the _k_-ring at that origin?

I might have more questions, but let's get those fundamentals in place first!

**Comment by nrabinowitz** [comment]
> A k-ring is a patch, a solid regular/symmetrical shape unless it touches a pentagonal distortion, in which case the ring is still well-defined, only its shape is not regular. That explains why the function kRing may contain holes instead of having exactly maxKringSize elements, correct?

Yes, that's right.

> Is kRingDistances like kRing plus distances for each hexagon? Do the array of indexes and the array of distances match each other one-to-one, where out[i] is at distance distances[i] of the origin?

Yes, also correct. Most of the bindings actually output `kRingDistances` as a 2D `H3Index[][]` array, where each array in the outer list represents one ring all the same distance from the origin.

> Then, I guess that the k-hexRing at origin H consists of the set difference of the k and k – 1 rings at origin H for k > 1, and exactly 0-ring for k = 0. That is, the perimeter of the ring so to speak.

Yes. The `hexRing` function returns all indexes exactly k steps away from H, which is the hollow ring.

> Also, hexRings can be discontinuous if they traverse pentagonal distorsions, but in that case they are still defined. Correct?

This ought to be true, but isn't in practice - if the `hexRing` function encounters pentagonal distortion, it currently fails with an error code. I think the only way to actually retrieve a distorted ring right now would be to take `kRingDistances` and filter on the desired ring distance.

> If I got that right, then, what is a range?

Yeah, the naming here isn't great. See #42 for more discussion. Basically, `hexRange` is just an optimized version of `kRing` that a) guarantees order in increasing distance from the origin (i.e. all ring 1 hexes, then all ring 2 hexes, etc), and b) fails if it encounters pentagon distortion.

I just added a benchmark I'll put up a PR for soon - the performance difference isn't very big, roughly 5%, so most users should simply use `kRing`. Under the hood, `kRing` tries to use `hexRange` and falls back to a slower algo if it encounters distortion. I think we could actually get rid of the 5% difference with some optimization work, but the `kRing` caller doesn't necessarily know whether they have distortion in the output or not.

**Comment by fxn** [comment]
Awesome reply, thanks very much!

Let me ask a couple related things more.

The indexes passed as input to `hexRanges` are required to be in the same resolution level? In theory the thing this function computes does not seem to need to assume that right? Each range would have the resolution of each corresponding origin and done.

On the other hand, I see giving indexes at different resolution levels is an error condition for `h3Distance`. The [traversal](https://github.com/uber/h3/blob/master/docs/api/traversal.md) document does not say the same for `h3Line` and `h3LineSize`... do these have the same requirement?

**Comment by nrabinowitz** [comment]
> The indexes passed as input to hexRanges are required to be in the same resolution level? In theory the thing this function computes does not seem to need to assume that right? Each range would have the resolution of each corresponding origin and done.

I believe there's no restriction specifically for `hexRanges`, but as a rule most H3 functions that take more than one index as input are intended to work on indexes of the same resolution (the exception being `uncompact`, which expects multi-resolution input). The `h3Distance` and `h3Line` functions rely on traversal of the grid space, which does not include any notion of traversal between resolutions, so mixed-resolution input would be an error (and [will return an error code](https://github.com/uber/h3/blob/master/src/apps/testapps/testH3Distance.c#L166)). I believe `h3SetToLinkedGeo` will work with multiple resolutions in some cases, returning different polygons for different resolutions, but this behavior is not guaranteed by the API and might have bad edge cases. All of the unidirectional edge functions rely on neighboring hexes being the same resolution, and will fail with mismatches.

**Comment by fxn** [comment]
Awesome @nrabinowitz, that was really helpful to have a better mental model.

Thanks!
