### ISSUE TITLE
Add function to get all base cells

### ISSUE THREAD

**Issue by nrabinowitz** [uber/h3#174]
You can get all base cells now by taking a 10-ring of some arbitrary base cell, but that's a bit hidden - it would be nice to offer all 122 base cells in order, through a function like `getBaseCells`.

**Comment by dfellis** [comment]
This would be a very simple bit of bit twiddling that could be done in a for loop (or just hardwired like the `numHexagons` function). What's the particular use case, however?

**Comment by zachasme** [comment]
I had not thought of taking the 10-ring of a basecell, and we wanted to allow a client to access the basecells from our bindings. So, yes, we ended up with a for loop using `H3_INIT`, `H3_SET_MODE`, `H3_SET_BASE_CELL`. But they are not in `h3api.h` so we had to copy them over. I felt this was somewhat inelegant.

I would like to make a pull request for this.

**Comment by nrabinowitz** [comment]
The other use case here is to facilitate iteration of all cells at a given resolution, which is relatively straightforward with h3ToChildren if you have a list of all base cells.
