### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by kaspermarstal** [uber/h3#18]
Is it possible to calculate the distance in kilometers between the centers of two arbitrary hexagons using h3?

**Comment by dfellis** [comment]
You can use `h3ToGeo` to get the center coordinates of each hexagon and then use [the Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) or [Vincenty's Formula](https://en.m.wikipedia.org/wiki/Vincenty%27s_formulae) to calculate the distance between them, depending on the speed vs accuracy trade-off you wish to make.

**Comment by kaspermarstal** [comment]
Wow, thanks for the example and for opening #23! We would be happy to contribute a pull request with this functionality (under your specifications of course).
