### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zachasme** [uber/h3#180]
Hi there! It would be very helpful if you could roll out a new minor release in the near future now that my two pull requests have been merged. I have some pending changes in my PostgreSQL bindings that depend on them.

**Comment by nrabinowitz** [comment]
Sorry, we've been a bit slow lately. I'll put up a new release today.

**Comment by nrabinowitz** [comment]
Released! https://github.com/uber/h3/releases/tag/v3.4.0

**Comment by zachasme** [comment]
Many thanks!
