### ISSUE TITLE
missing java implementation of h3Line

### ISSUE THREAD

**Issue by davidfauth** [uber/h3#185]

**Comment by davidfauth** [comment]
maybe I'm missing something but I don't see the h3Line in the java api. Using 3.2.0

**Comment by dfellis** [comment]
`h3Line` was added in [H3 v3.3.0](https://github.com/uber/h3/blob/master/CHANGELOG.md#330---2018-12-25) hence why it's not in H3-Java v3.2.0 (the major and minor of the C code and the official bindings line up). The Java library needs updating (but I believe the primary maintainer of that binding is currently on vacation).

**Comment by davidfauth** [comment]
Thanks.
