### ISSUE TITLE
Find the derivations of H3

### ISSUE THREAD

**Issue by Slawlight** [uber/h3#187]
Where can I find the detail derivation of the conversion between these coordinates?  Could you please give me some papers about H3?

**Comment by nrabinowitz** [comment]
There's a reasonable overview of the grid system in the docs: https://uber.github.io/h3/#/documentation/core-library/overview

This also references [a paper by Sahr et al on discrete global grid systems](http://webpages.sou.edu/~sahrk/sqspc/pubs/gdggs03.pdf) that provides some of the research background for the library.

**Comment by Slawlight** [comment]
Thank you very much
