### ISSUE TITLE
 h3/examples/index.c not working

### ISSUE THREAD

**Issue by rachelglenn** [uber/h3#192]
Hi, I am doing the exact same thing as the index.c file. My input latitude of 32.0 long of -79.0 and I get a latitude of 0.558505 and longitude of -1.378984. Should it give back the same latitude and longitude.

**Comment by isaacbrodsky** [comment]
Hi, those looks like the expected coordinates in radians. Could you check if you are converting the coordinates back from radians, used in the library, to degrees? (https://github.com/uber/h3/blob/master/examples/index.c#L48)
