### ISSUE TITLE
Rename hexAreaM2 and edgeLengthM

### ISSUE THREAD

**Issue by wwchen** [uber/h3#202]
The functions `hexArea(Km|m)2` and `edgeLength(Km|M)` is a bit misleading, given the fact each edge and hex area are not made equally. Additionally, there are 12 pentagons that do not conform. Given these functions actually produce the _average_ size, I recommend renaming these to `averageHexArea(Km|m)2` and `averageEdgeLength(Km|M)`

**Comment by wwchen** [comment]
Following this, I propose `hexArea(Km|m)2` and `edgeLength(Km|M)` to take in `H3Index` as argument and produce the _exact_ area/length

**Comment by ajfriend** [comment]
Closing this, as I think we've agreed on these changes with #308.

@wwchen, let me know if you disagree and we can re-open!
