### ISSUE TITLE
Existence of heptagon at odd-numbered resolutions

### ISSUE THREAD

**Issue by billyauhk** [uber/h3#208]
I have written some short code to exhaustively lists all the H3 cells at a given resolution in order to investigate their properties. My result shows there are heptagons (7-sided cells) at odd-numbered resolutions.

I think these should be documented, especially with h3IsPentagon() function one might not expect there exists cells which is neither pentagon and hexagon.

(Edit: It seems there are also octagon (8-sided) and decagon (10-sided) there...)

**Comment by nrabinowitz** [comment]
This is documented, though not highlighted, here: https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary

The quick version is that cell edges crossing an icosahedron edge have an additional distortion vertex inserted at the intersection point. This means that cells intersecting the icosahedron edges may have 7, 8, or (in the case of pentagons) 10 vertices. This only applies to cells in "Class III" resolutions, which are the odd-numbered resolutions (though you can also check with `h3IsResClassIII(h3Index)`).

I increasingly feel like we ought to have a specific documentation page highlighting the irregularities of the grid: Pentagons, distortion vertices, variations in area and edge length.

**Comment by nrabinowitz** [comment]
Opened #209 to track better docs.

**Comment by Fil** [comment]
I just made an exploration notebook about this topic
https://observablehq.com/@fil/h3-oddities

Comments welcome
