### ISSUE TITLE
Hexagons that cross antimeridian need all positive or negative longitudinal coordinates

### ISSUE THREAD

**Issue by usuallycwdillon** [uber/h3#211]
Hexagons that cross the antimeridian need to have longitudinal vertex coordinates that are all positive or all negative to render correctly.  For example, H3 address `840d919ffffffff` has coordinates at 
`[[[179.71784991825572,66.68413733723276],[179.37545368087038,66.47472723489929],[179.65328295314654,66.25843462773057],[-179.7336351882172,66.24972734799263],[-179.38719513936746,66.4567370298999],[-179.6577425262902,66.67484776621974],[179.71784991825572,66.68413733723276]]]`

but could instead be `[[[179.71784991825572,66.68413733723276],[179.37545368087038,66.47472723489929], [179.65328295314654,66.25843462773057],[180.2663648,66.24972734799263],[180.6128049,66.4567370298999],[180.3422575,66.67484776621974],[179.71784991825572,66.68413733723276]]]`

so that edges do not get drawn around the globe (alternatively, it could have all longitudinal vertices in the `-179.xx to -180.xx` range). 

The nine resolution 4 hexagons that cross the antimeridian in Russia render correctly with "out of bounds" longitude coordinates here: https://gist.github.com/usuallycwdillon/b10be791297fb83b41260393aee030e3
but are are incorrect here: https://github.com/usuallycwdillon/hexJet/tree/master/src/main/resources/historicalHexMaps/1815

This can also be reproduced by referencing those H3 hexagons by address in kepler.gl (probably, because it's also using MapBox).  Even though longitude values > |180| are supposed to be invalid in some coordinate systems (like WGS84, EPSG:4326), GIS software should handle it. I don't use ArcGIS, but QGIS wraps these hexagons around the globe if longitude value signs are mixed but displays them correctly when the coordinates are "invalid".

**Comment by nrabinowitz** [comment]
For the core H3 library, we'd prefer to err on the side of correctness, which in this case means outputting longitude values in the valid range. While this is a valid concern, I don't think we'll address it in the core library. This should probably be a feature request against Mapbox (choosing arcs < 180 when faced with two valid choices, or respecting a right-hand rule).

For Javascript, I have a helper here: https://observablehq.com/@nrabinowitz/mapbox-utils - admittedly this isn't going to be very efficient going through thousands of hexagons.
