### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [uber/h3#216]
Would you like to [add more error handling](https://github.com/uber/h3/blob/36a2cebd1cd292cfcfe171626df666d1885c0f18/src/h3lib/lib/algos.c#L160 "Update candidate: kRing()") for return values from [calls of the function “malloc”](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation")?

**Comment by isaacbrodsky** [comment]
This is a planned improvement, but will be released as version 4.0.0 of the library (#104) because of the breaking change to function signatures.

**Comment by isaacbrodsky** [comment]
Completed in H3 v4.0.0.
