### ISSUE TITLE
PostGIS integration

### ISSUE THREAD

**Issue by Komzpa** [uber/h3#217]
Hi,

I'm looking at integrating H3 support into PostGIS. H3 is licensed as Apache, so I can't use the library directly - PostGIS is licensed GPL2+ which seems to be incompatible.

Can we get h3 dual licensed, Apache + GPL2+? Are there other options of getting H3 grid support in GPL2+ software?

**Comment by dfellis** [comment]
So [Apache is compatible with GPL3-licensed code](http://www.gnu.org/licenses/license-list.en.html#apache2). Could that integration code simply be licensed GPL3 with a compile-time flag to remove it when a user wants to keep GPL2 compatibility?

I'm not a lawyer and don't work at Uber, anymore, but I don't expect the dual licensing to happen.

**Comment by isaacbrodsky** [comment]
Hi @Komzpa, thanks for reaching out. We do not plan to dual license H3 at this time.

**Comment by ppKrauss** [comment]
In nowadays you can "plug and  play", see https://pgxn.org/dist/h3/1.0.6/ ([git](https://pgxn.org/dist/h3/1.0.6/))
