### ISSUE TITLE
Earth Radius

### ISSUE THREAD

**Issue by rachelglenn** [uber/h3#218]
Hi, I am wanting to use H3 for a different planet with a different radius. Will H3 still work if the Earth Radius is changed?

**Comment by nrabinowitz** [comment]
Going through the code, the only place that the `EARTH_RADIUS_KM` constant is used is in calculating distances, which we use internally in `polyfill` - even in this case, I'm pretty sure the unit isn't relevant to the external consumer. Obviously the `edgeLength` and `hexArea` functions will not return correct values, but I *think* the rest of the library will work fine for spheres of arbitrary size.

Purely out of curiosity, what planet are you planning to use it for?

**Comment by dfellis** [comment]
Planning something @nrabinowitz ? ;)

![The Conquest for the Planet X](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FvZYBGrK6aIw%2Fhqdefault.jpg&f=1)

**Comment by rachelglenn** [comment]
I like the cartoon. I was thinking Mars and was hoping I could get away
with changing the radius to accomplish it.

Thank you,

-Rachel
