### ISSUE TITLE
Rotation and Overage

### ISSUE THREAD

**Issue by helloniuniu** [uber/h3#226]
I suggest adding Face Numbers to the H3Index to reduce rotation and overage code.

**Comment by RichardVasquez** [comment]
Are you talking about something other than the 7 bits encoded for the face as shown at
https://uber.github.io/h3/#/documentation/core-library/h3-index-representations

There's also an API call to recall the face with h3GetBaseCell shown at https://uber.github.io/h3/#/documentation/api-reference/inspection

**Comment by sahrk** [comment]
@RichardVasquez those 7 bits encode the 122 resolution 0 base cells that are the root of the aperture 7 indexing hierarchies, not the 20 faces of the icosahedron.

**Comment by RichardVasquez** [comment]
@sahrk Ah.  I misunderstood.  I see what OP was saying now.  The question would be where to place the required 5 bits, as there doesn't seem to be more than one free bit available at this time.

I would imagine that creating an API access point would be simpler in terms of code, perhaps something like `getFace(H3Index h3)`?  This would still leave open, IMO, the issue of what face is a pentagon on?

**Comment by sahrk** [comment]
@RichardVasquez many of the base cell hexagons also lie on an icosahedron edge (and hence on two faces).

**Comment by isaacbrodsky** [comment]
Hi, as @sahrk mentioned a cell can't necessarily be associated to a single face, and introducing new information to the H3 index structure would be a significant change to the library.
