### ISSUE TITLE
_h3ToFaceIjk

### ISSUE THREAD

**Issue by helloniuniu** [uber/h3#230]
if the param substrate=0, it seems to be no way of judging the edge here.
Maybe I misunderstood, but I don't really understand.

`
   if (_adjustOverageClassII(fijk, res, pentLeading4, 0)) 

int _adjustOverageClassII(FaceIJK* fijk, int res, int pentLeading4, int substrate)//substrate=0
{
    int overage = 0;

    CoordIJK* ijk = &fijk->coord;

    // get the maximum dimension value; scale if a substrate grid
    int maxDim = maxDimByCIIres[res];

    if (substrate) maxDim *= 3;

    // check for overage
    if (substrate && ijk->i + ijk->j + ijk->k == maxDim)  // on edge
        overage = 1;
`

**Comment by isaacbrodsky** [comment]
I believe this is because only the function involved with getting the boundary of a cell use a substrate grid (https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary). The function calls with `substrate=0` are related with finding the FaceIJK coordinates of the cell, not the coordinates of the cell vertices.

**Comment by helloniuniu** [comment]
> 我相信这是因为只有获取细胞边界所涉及的功能才使用基质网格（https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary）。函数调用与`substrate=0`查找单元格的FaceIJK坐标有关，而与单元顶点的坐标无关。



> I believe this is because only the function involved with getting the boundary of a cell use a substrate grid (https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary). The function calls with `substrate=0` are related with finding the FaceIJK coordinates of the cell, not the coordinates of the cell vertices.

**Comment by helloniuniu** [comment]
> > 我相信这是因为只有获取细胞边界所涉及的功能才使用基质网格（[https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary）。函数调用与`substrate=0`查找单元格的FaceIJK坐标有关，而与单元顶点的坐标无关。](https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary%EF%BC%89%E3%80%82%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E4%B8%8E%60substrate=0%60%E6%9F%A5%E6%89%BE%E5%8D%95%E5%85%83%E6%A0%BC%E7%9A%84FaceIJK%E5%9D%90%E6%A0%87%E6%9C%89%E5%85%B3%EF%BC%8C%E8%80%8C%E4%B8%8E%E5%8D%95%E5%85%83%E9%A1%B6%E7%82%B9%E7%9A%84%E5%9D%90%E6%A0%87%E6%97%A0%E5%85%B3%E3%80%82)
> 
> > I believe this is because only the function involved with getting the boundary of a cell use a substrate grid (https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary). The function calls with `substrate=0` are related with finding the FaceIJK coordinates of the cell, not the coordinates of the cell vertices.

Thank you very much!

**Comment by helloniuniu** [comment]
> I believe this is because only the function involved with getting the boundary of a cell use a substrate grid (https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeoboundary). The function calls with `substrate=0` are related with finding the FaceIJK coordinates of the cell, not the coordinates of the cell vertices.

I see. we just need to determine whether an overage exists by taking the sum of the ijk components,and if there is an overage the positive ijk components indicate which adjacent face the cell center lies on.Otherwise, the cell center point falls on the same icosahedron face as its base cell
