### ISSUE TITLE
Add h3GetFaces

### ISSUE THREAD

**Issue by nrabinowitz** [uber/h3#236]
Knowing that two cells are on different faces of the icosahedron can be useful for rendering, because they will have different shape distortions. This has come up in the deck.gl integration ([see e.g. this PR](https://github.com/uber/deck.gl/pull/3103)), and it should be trivial to add an util like `h3GetFace` to return the face number 0-20.

**Comment by sahrk** [comment]
I'm pretty sure this was discussed on another issue, but remember that many hexagons straddle an icosahedron edge and are therefore on two faces geometrically, and all pentagons straddle five faces. The assignment of cells to a single face is only to specify their home ijk coordinate system.

**Comment by nrabinowitz** [comment]
@sahrk - that's a good point, but shouldn't affect this particular use case. Worth noting in docs though.

**Comment by sahrk** [comment]
I guess I'm unclear on this use case, but just to clarify note that this
means that different parts of the same single hex can have different shape
distortion.

**Comment by Pessimistress** [comment]
Speaking for my own use case -- if there is a way for me to tell whether a hexagon sits on an icosahedron edge, similar to `isPentagon`, that will suffice too.

**Comment by sahrk** [comment]
There is code in `_h3ToFaceIjk` that determines if a hexagon sits on an edge ([see explanation in the documentation](https://uber.github.io/h3/#/documentation/core-library/walkthrough-of-h3togeo)). It should be straight-forward to extract that code into a separate function.

**Comment by nrabinowitz** [comment]
Hm. I think for the current use case, `h3GetFace` is going to be the simplest to implement and may be more generally useful for rendering issues than `h3IsOnFaceEdge` (though this would be useful for the proposed vertex mode in #96).  I think we'd punt on pentagons entirely and return `-1`; for other cells, returning the "home" face and then additionally offering `h3IsOnFaceEdge` for consumers that need to handle this case might make sense.

I'm inclined to implement `h3GetFace` now, because it's fast and simple, and handle our literal edge cases in another function.

**Comment by isaacbrodsky** [comment]
> Hm. I think for the current use case, h3GetFace is going to be the simplest to implement and may be more generally useful for rendering issues than h3IsOnFaceEdge (though this would be useful for the proposed vertex mode in #96).

If the problem is that the cells have different shape distortions arising from different projections, would implementing an `h3GetProjection` be more in line with what the user is looking for?

>  I think we'd punt on pentagons entirely and return -1; 

I feel we should be a little cautious about adding functions which are not defined for valid indexes. It gives me the impression that our definition of the function may not be as good was we want, and I am concerned the edge cases complicate the API.

> for other cells, returning the "home" face and then additionally offering h3IsOnFaceEdge for consumers that need to handle this case might make sense.

Couldn't a cell have its home face on one face and be located entirely on another face (and thus not be on an edge)? I don't have an index on hand to demonstrate this but I believe for examples one of the descendants of the base cell 31 (which is at `(2, 2, 0)` on face 0) should have this property.

Another option is maybe we are trying to define a `h3EntirelyContainedByFace` (which seems to require `h3IsOnFaceEdge`).

**Comment by sahrk** [comment]
> Couldn't a cell have its home face on one face and be located entirely on another face (and thus not be on an edge)?

Yes. A cell on the edge will have approximately half of its indexing descendants on a different face than  its home face. The trivial version of `h3GetFace` would return the face of the base cell (which could be a pentagon).

**Comment by nrabinowitz** [comment]
> If the problem is that the cells have different shape distortions arising from different projections, would implementing an h3GetProjection be more in line with what the user is looking for?

What would this return?

**Comment by nrabinowitz** [comment]
> Yes. A cell on the edge will have approximately half of its indexing descendants on a different face than its home face. The trivial version of h3GetFace would return the face of the base cell (which could be a pentagon).

I don't think that was what I was proposing - I was basically thinking
```
FaceIJK fijk;
_h3ToFaceIjk(h3, &fijk);
return fijk.face;
```
Which I *think* returns the actual face the cell is on, except in the case of cells on an edge (please correct me if I'm wrong here).

**Comment by sahrk** [comment]
Now I understand, sorry. You are correct, `_h3ToFaceIjk` will return the
face that the cell actually lies on.

**Comment by sahrk** [comment]
Now I understand, sorry. You are correct, `_h3ToFaceIjk` will return the
face that the cell actually lies on.

**Comment by isaacbrodsky** [comment]
> > If the problem is that the cells have different shape distortions arising from different projections, would implementing an h3GetProjection be more in line with what the user is looking for?
> 
> What would this return?

I'm thinking it could return the face number if entirely contained on that face, an edge number if on an edge, or a pentagon number. The new numberings would be chosen so they are not the same as the face number. The result is intended to indicate which cells have the same shape distortion.

**Comment by nrabinowitz** [comment]
Hm. For the immediate case, I think the implementation I suggest above would be sufficient. @isaacbrodsky's idea of a "projection" integer is an interesting one, as long as the projections are considered opaque (e.g. I'm not a fan of checking some secret property of the returned integer to see if it lies on an edge). Returning special values for edges complicates the implementation quite a bit, particularly if I need the same edge to return the same number regardless of the base cell of the index.

Thoughts on `experimentalGetProjection`, which would return the face number (0-20) or, say, 20 + base cell number for pentagons, but which would not handle the edge case?

**Comment by dfellis** [comment]
What about returning an array of 1-5 integers for all of the faces involved? Most of the time only one would be returned, hexagons on edges would return 2 integers, and the pentagons would return 5. It would probably make sense to call it `h3GetFaces` at that point.

Then it would be more obvious to upstream use-cases what's going on and they can do what they want with the info. Plus you get the added bonus of being able to make a Monty Python reference in the code ("1, 2, 5!")

**Comment by nrabinowitz** [comment]
> What about returning an array of 1-5 integers for all of the faces involved? Most of the time only one would be returned, hexagons on edges would return 2 integers, and the pentagons would return 5. It would probably make sense to call it h3GetFaces at that point.

I like that, though again it's harder to implement. Was really looking for a 2-liner here :). This is probably the clearest proposal from an API perspective however.

> Plus you get the added bonus of being able to make a Monty Python reference in the code ("1, 2, 5!")

Only in the Python binding. It's the law.

**Comment by nrabinowitz** [comment]
Following up on this: I agree that `h3GetFaces` is the more defensible interface, but for the specific rendering use case (which is basically "can I be reasonably sure, very quickly, that all hexagons in a given set are on the same face"), `h3GetFace` might actually be better (because it's presumably faster), and could be implemented quickly.

What are your collective thoughts on offering *both* `h3GetFace`, which would just return `fijk.face` and would be accompanied by a bunch of caveats, and `h3GetFaces`, which would return an up-to-5 element array and be slower but more correct?

**Comment by isaacbrodsky** [comment]
I am hesitant to add a `h3GetFace` (get home face) function because of the limitations about cells actually straddling more than one face. I don't believe the home face concept is familiar to users, and so am concerned the API might be difficult to use and to have as part of the public API.
