### ISSUE TITLE
Projection 

### ISSUE THREAD

**Issue by helloniuniu** [uber/h3#237]
From the document ,I knew that the hexagonal grid system is created on the planar faces of a sphere-circumscribed icosahedron, and the grid cells are then projected to the surface of the sphere using an inverse face-centered polyhedral gnomonic projection.
The outstanding (and only useful) feature of the gnomonic projection results from the fact that each great-circle arc，the shortest distance between any two points on the surface of a sphere, lies in a plane passing through the center of the globe. Therefore, all great-circle arcs project as straight lines on this projection.The scale is badly distorted along such a plotted great circle, but the route is precise for the sphere.
Although the calculation can be simplified by using the face-centered gnomonic projection,the distortion and scale rapidly increase away from the center.
![11111](https://user-images.githubusercontent.com/37333122/57899804-faceee80-7890-11e9-81e9-219158a3baba.jpg)
So,Why not choose Snyder Equal-area Map Projection?

**Comment by sahrk** [comment]
The only advantage of the ISEA projection is that it is equal area. If your use case is performing statistical analysis on static global data sets binned into a grid it is a good choice. But if you are using it to capture the locations of moving objects (like cars) then note that straight lines on the ISEA plane do not map to great circles on the sphere. This also means that cells in an ISEA grid are not spherical polygons; they have no exact representation using great circles. Perhaps more importantly, the ISEA projection is significantly slower than the gnomonic, which is an issue if you're trying to ingest as much real-time geospatial data as Uber. Also note that, though the gnomonic projection is not equal area, the change in area varies gradually across the surface of the sphere. So within a region like a city the areas will be relatively close to equal.

**Comment by helloniuniu** [comment]
> The only advantage of the ISEA projection is that it is equal area. If your use case is performing statistical analysis on static global data sets binned into a grid it is a good choice. But if you are using it to capture the locations of moving objects (like cars) then note that straight lines on the ISEA plane do not map to great circles on the sphere. This also means that cells in an ISEA grid are not spherical polygons; they have no exact representation using great circles. Perhaps more importantly, the ISEA projection is significantly slower than the gnomonic, which is an issue if you're trying to ingest as much real-time geospatial data as Uber. Also note that, though the gnomonic projection is not equal area, the change in area varies gradually across the surface of the sphere. So within a region like a city the areas will be relatively close to equal.

**Comment by helloniuniu** [comment]
Perfect explanation! Thank you very much.
