### ISSUE TITLE
Add configurable memory management routines

### ISSUE THREAD

**Issue by coconut2015** [uber/h3#241]
I briefly looked some of the h3lib code via web interface, and they use malloc / free.  Forgive me if h3lib can already configure to be used with other memory management routines.

I am wondering if it is possible to add configurable memory management routines other than malloc / free.  I could certainly modify the code myself, but then it would create an upgrade / merge issue.

Basically, I am interested in using H3 as embedded functions in databases.  PostgreSQL for instance would have its own set of routines.

https://www.postgresql.org/docs/current/spi-memory.html

Other databases such as DB2 that support C UDF could face the similar issue.

Thanks.

**Comment by dfellis** [comment]
H3's API is designed such that the vast majority of memory usage is passed in by the consumer of the API. See for instance [maxH3ToChildrenSize](https://github.com/uber/h3/blob/master/src/h3lib/lib/h3Index.c#L158) and [h3ToChildren](https://github.com/uber/h3/blob/master/src/h3lib/lib/h3Index.c#L192), which are paired functions to first estimate how much memory you need to allocate, and then given a chunk of allocated memory, perform the operation.

The vast majority of the time when `malloc`/`free` is used, it's internal only and the memory is freed before the return value provided. The only exception I'm aware of is the [h3SetToLinkedGeo](https://github.com/uber/h3/blob/master/src/h3lib/lib/algos.c#L799) function, but cleanup logic is wrapped in the [destroyLinkedPolygon](https://github.com/uber/h3/blob/master/src/h3lib/lib/linkedGeo.c#L107) function for the end-user.

This API design decision is what has made binding into Java, Python, and Go relatively simple, with the Python bindings living in [basically a single file](https://github.com/uber/h3-py/blob/master/h3/h3.py) with low cyclomatic complexity.

Finally, I'll note that there are [multiple](https://github.com/bytesandbrains/h3-pg) [database](https://github.com/davidfauth/Neo4jH3) bindings already written for H3, so the minimal use of `malloc` and `free` has not been a blocker for database integrations. :)

**Comment by coconut2015** [comment]
The reason why I am requesting the feature is because **any** use of malloc / free, even if for a brief window, can cause memory leak or corruption in MPP environments where threads can be suspended / killed at any given time (unless specific protection is made).  malloc / free also use synchronization primitives that may not be compatible with whatever main MPP program's thread / synchronization mechanisms.

So, I am asking if H3 could refactor the code such that it uses h3Malloc / h3Free instead of generic malloc / free and put the definition of h3 memory management routines in a config file that can be easier maintained.

**Comment by isaacbrodsky** [comment]
I think this is something we'd be interested in adding, either adding functions that you can pass in memory allocated using your allocator, as can already be done with calling `kRingDistances` instead of `kRing`.

Allowing you to configure the memory manager seems like a reasonable request. Are you looking for the ability to do that at runtime, or would compile time replacement (via `#define`) be sufficient?

**Comment by coconut2015** [comment]
#define is sufficient.
