### ISSUE TITLE
add `pentagonsAtRes` function?

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#255]
Shall we add a function like `pentagonsAtRes(int res, H3Index* out)` which would provide the user with the set of pentagon cells at any given resolution?

@nrabinowitz mentioned that we might be able to do this with something like

```
setH3Index(&myH3Index, res, <some_pentagon_base_cell_index>, 0);
```

where the pentaton base cells are: `4, 14, 24, 38, 49, 58, 63, 72, 83, 97, 107, 117`

**Comment by dfellis** [comment]
It would be a simple function to write. Just set the mode bit, base cell, and resolution, then zero the child numbers until you reach the resolution and then set the child numbers to 7 after that until you hit res 15.

Is there a use-case for it outside of writing tests that involve pentagons? That might be enough of a justification for it, but I would feel better if you've got something in mind for it. ;)

**Comment by ajfriend** [comment]
In addition to tests, if users are concerned about performance hits in their calculations, they might want to know ahead of time where the pentagons are.

**Comment by ajfriend** [comment]
Alternatively, we could also have a function that just returns the icosahedron vertices.

**Comment by nrabinowitz** [comment]
> Alternatively, we could also have a function that just returns the icosahedron vertices.

That might be useful - I've been thinking about `getIcosahedronFaces` anyway as a companion to `h3GetFaces` (right now there's no way for an external consumer to match a face index to its coordinates). But the two aren't mutually exclusive.

**Comment by dfellis** [comment]
I'm not opposed to any of these, but @isaacbrodsky had issues when I brought it up before because these are non-H3Index things that have to be documented and the increase in the API surface area and could confuse newcomers, as I recall.

**Comment by nrabinowitz** [comment]
> I'm not opposed to any of these, but @isaacbrodsky had issues when I brought it up before because these are non-H3Index things that have to be documented and the increase in the API surface area and could confuse newcomers, as I recall.

I definitely see this concern, but I think we should consider new features if they are hard or impossible to implement outside H3, and easy to implement inside.

- For pentagons, I can't think of an easy way to get all the res 10 pentagons outside the C library, without reverse-engineering the necessary bit operations. I suppose you could do it iteratively, something like
```
let pentagons = h3.getRes0Indexes().filter(h3.h3IsPentagon);
for (let res = 1; res < 10; res++) {
  pentagons = pentagons.map(index => h3.h3ToChildren(index, res)[0]);
}
```
That's not too bad, but not self-evident, and much slower than the bitwise op.

- For the icosahedron, your only option would be use the [icosahedron KML file](https://github.com/uber/h3/blob/master/KML/icosa.kml) or copy/paste the face definitions out of the source code.

Both of these might meet the requirements above, as they're difficult outside H3 and only a few extra lines inside - basically the only cost is increasing the surface area of the API.

**Comment by isaacbrodsky** [comment]
I am definitely sensitive to increasing the API surface and complexity in working with the library. I'd like to explore if this is the best addition to the library to implement this. The pentagons are something we already expose directly to the user, so maybe `pentagonsAtRes` is okay. 

`h3ToChildren` above has an issue where you need to determine all of the children in order to find the center child at a finer resolution. Would `h3ToCenterChild(H3Index parent, int res)` be helpful instead?

**Comment by dfellis** [comment]
Oh, I wasn't expecting any resistance to `pentagonsAtRes`, only the `getIcosahedronFaces` and similar functions. And again I personally view them as worthwhile additions to the API. If they're documented in a separate section from the rest of the library (similar to how the unidirectional edges are) and it's explicitly called out that it's for advanced use-cases only as it deals with the implementation of H3 itself, I think it can be safe to add to the API and expose things that @nrabinowitz has pointed out are not really doable without brittle reverse-engineering of this library.
