### ISSUE TITLE
The return value of 'sscanf()' should be checked 

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [uber/h3#270]
https://github.com/uber/h3/blob/29790abd3f1fc4cde4511405b04497693fdcb7bd/src/h3lib/lib/h3Index.c#L52

**Comment by isaacbrodsky** [comment]
Hi, as mentioned in the comment above that line (https://github.com/uber/h3/blob/29790abd3f1fc4cde4511405b04497693fdcb7bd/src/h3lib/lib/h3Index.c#L51), if the parsing fails I believe `h` will be unmodified, and an error value (0) will be returned. This seems to cover all error cases from `sscanf`.
