### ISSUE TITLE
Relation to DGGRID

### ISSUE THREAD

**Issue by r-barnes** [uber/h3#28]
In the README, I see:

> DGGRID Copyright (c) 2015 Southern Oregon University

What is the relationship between H3 and DGGRID?

**Comment by sahrk** [comment]
We borrowed the basic hex grid quantification code from DGGRID. That is the
only relationship between the two.

**Comment by dvanduzer** [comment]
One of the most obvious differences for users of DGGRID: Aperture 4 (ISEA4H) cells at resolution 13 are about the size of H3 cells at resolution 8.

**Comment by sahrk** [comment]
DGGRID implements an entirely different set of grids. DGGRID has aperture 3
and 4 hex grids using the ISEA or Fuller projections. H3 implements a
hierarchically indexed aperture 7 grid (off of an initial aperture 43
sequence) using the gnomonic projection.
