### ISSUE TITLE
About  Hexagon at the junction of different cities 

### ISSUE THREAD

**Issue by wangzi6578** [uber/h3#286]
Hi,there,
  I'm curious about the relationship between hexagon and city. 1 to N? or N to N?  Can each hexagon belong to a different city.

**Comment by dfellis** [comment]
I think there's a bit of a confusion of what H3 does?

At res 0, a single hexagon not only engulfs a whole city or multiple cities, but it can engulf multiple _countries_.

![Screenshot_20191030_084915](https://user-images.githubusercontent.com/765551/67874716-8e6c4280-faf2-11e9-8566-5edd7bf0d930.png)

Those hexagons can be subdivided and subdivided again (up to 16 divisions in total), like so:

![Screenshot_20191030_085358](https://user-images.githubusercontent.com/765551/67874939-ea36cb80-faf2-11e9-979c-008f19d2da76.png)

This picture above is closer to city-level sizes (at res 3). It can be divided down to about the size of a coffee table (about 0.9 square meters) and at that resolution (res 15) you would be unlikely to ever have a hexagon that belongs to more than one city.

For a practical distinction when it might not be as clear-cut (say resolution 9 or 10 when we're dealing with hexagons slightly above or below the average city block size, and small cities that directly jut against each other), the [polyfill algorithm](https://uber.github.io/h3/#/documentation/api-reference/regions#polyfill) uses the centerpoint of the hexagon to assign containment within the given geofence or not, and provides guarantees that two contiguous polygons (eg, two city boundaries) will have contiguous, non-overlapping sets of hexagons, like in these 4 different polygons-mapped-to-hexagon-sets for different regions of San Francisco:

![sf-polyfill](https://eng.uber.com/wp-content/uploads/2018/06/image13-e1529950174302.png)

I hope that clears things up?
