### ISSUE TITLE
lat/lng normalization

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#287]
([Based on this discussion in `h3-py`.](https://github.com/uber/h3-py/pull/79#discussion_r341883616))

Which of the following should `h3.geo_to_h3(37.3615593 + 180.0, -122.0553238 + 360.0, 5)` evaluate to:

- `'85283473fffffff'`
- `'85ca2d53fffffff'`

Since `h3.geo_to_h3(37.3615593, -122.0553238, 5) == '85283473fffffff'`, it seems like the first option should be correct. However, there's potential disagreement between the C, Python, and JS bindings.

Probably, this logic should be handled by the core C library. If so, what's the right logic/formula here?

**Comment by ajfriend** [comment]
What's the right name for this concept? "normalization"? "standardization"?

**Comment by ajfriend** [comment]
I have what I think is the "right" way to do this normalization/standardization of lat/lng coordinates. 

Here's some Python code to do it:

```python
import numpy as np

def deg_mod(x):
    'Map x into the *half-open* interval [-180, 180)'
    
    return (x + 180.0) % 360 - 180

def deg_std(lat, lng):
    """ Coerce lat/lng into standard representation
    
    lat in [-90, 90] (up and down)
    lng in [-180, 180) (around the globe, looking down)
    """
    
    lat = deg_mod(lat)
    
    # if lat is on the wrong side, we reflect
    # it around the north/south pole and
    # adjust the lng accordingly
    if abs(lat) > 90:
        lat = np.sign(lat)*180 - lat
        lng += 180
    
    lng = deg_mod(lng)
    
    return lat, lng
```

`deg_std` makes the following transformations between lat/lng pairs:

- `( 90, 0) -> ( 90,    0)`
- `( 91, 0) -> ( 89, -180)` 
- `(-91, 0) -> (-89, -180)`

**Comment by ajfriend** [comment]
Here's an example of discontinuity around the north pole with the current Python `master` branch.

```python
>>> eps = 1e-5
>>> print h3.geo_to_h3(90 + eps, 0, 5)
>>> print h3.geo_to_h3(90 - eps, 0, 5)
'85f29383fffffff'
'85032623fffffff'
```

We avoid the discontinuity by applying `deg_std`:

```python
>>> lat, lng = deg_std(90 + eps, 0)
>>> print h3.geo_to_h3(lat, lng, 5)

>>> lat, lng = deg_std(90 - eps, 0)
>>> print h3.geo_to_h3(lat, lng, 5)
'85032623fffffff'
'85032623fffffff'
```

**Comment by ajfriend** [comment]
For the notorious example above,

```python
>>> lat, lng = 37.3615593, -122.0553238
>>> print h3.geo_to_h3(lat,       lng, 5)
>>> print h3.geo_to_h3(lat + 180, lng, 5)

>>> lat, lng = deg_std(lat + 180, lng)
>>> print h3.geo_to_h3(lat,       lng, 5)
'85283473fffffff'
'85283473fffffff'
'85ca2d53fffffff'
```

Thus, I think we would want to have

```python
h3.geo_to_h3(37.3615593 + 180.0, -122.0553238 + 360.0, 5) == '85ca2d53fffffff'
```

This follows from the fact that, due to equivalence defined by `deg_std`, we should consider `(37.3615593 + 180.0, -122.0553238 + 360.0)` to be equivalent to `(-37.3615593, 57.9446762)`.

A little more abstractly, but in particular for `lat, lng = (37.3615593, -122.0553238)`, we would want to have

```python
deg_std(lat,       lng       ) == (lat, lng)
deg_std(lat,       lng + 360 ) == (lat, lng)
deg_std(lat + 360, lng       ) == (lat, lng)
```

and

```python
deg_std(lat + 180, lng       ) != (lat, lng)
deg_std(lat + 180, lng + 360 ) != (lat, lng)
```

(Note: These don't all actually evaluate to `True` in Python, due to floating point error. But you get the idea...)

**Comment by ajfriend** [comment]
Oooh, in fact, for any `(lat, lng)` pair, we should have the following two pairs are "equivalent":

```python
( lat + 180, lng      )
(-lat      , lng + 180)
```

Anyway, does all the stuff above make sense, and resolve how we should do normalization/standardization?

**Comment by ajfriend** [comment]
I think the current C library and the `cython` branch already handle this correctly, without the need for an extra `deg_std` function to do pre-processing.

For example, on the `cython` branch (if I define `deg_std` as above), I'll get the following output:

```python
>>> def foo(n, res=1):
>>>     for _ in range(n):
>>>         lat1, lng1 = np.random.randn(2)*360*2
>>>         lat2, lng2 = deg_std(lat1, lng1)
>>> 
>>>         out1 = h3.geo_to_h3(lat1, lng1, res)
>>>         out2 = h3.geo_to_h3(lat2, lng2, res)
>>>         
>>>         yield out1 == out2
>>>         
>>> all(foo(100000, 13))
True
```

That seems to suggest that there's no need to pre-process with `deg_std` and the raw C library should be handling it correctly.

@isaacbrodsky, the only weirdness is that you were getting `'85283473fffffff'` as the output for `h3.geo_to_h3(37.3615593 + 180.0, -122.0553238 + 360.0, 5)` in the C library, which disagrees with what I think is the correct result above. But the `cython` branch is calling the C library directly, and gets the "correct" result above. Were you using the command line tool from the C library? My only thought is that it might be doing some pre-processing like the [old mercator function](https://github.com/uber/h3-py/commit/963241447bba1151958199c6ac30d726c34a2345#diff-1df158fef384a0b5e893d1ef4a14c773L13-L20), which I think is actually incorrect.

**Comment by isaacbrodsky** [comment]
@ajfriend I was using the [geoToH3 filter](https://github.com/uber/h3/blob/master/src/apps/filters/geoToH3.c) I might have made an error about which index the C library was giving me. I reran this and got the following:

```
MINGW
$ ./bin/Debug/geoToH3 --resolution 5 --latitude 217.3615593 --longitude 237.9446762
85ca2d53fffffff

Debian
$ ./bin/geoToH3 --resolution 5 --latitude 217.3615593 --longitude 237.9446762
85ca2d53fffffff
```

**Comment by ajfriend** [comment]
OK then! It sounds like the C library, `cython` branch, and the JS bindings all agree that the right answer is `'85ca2d53fffffff'`. 

The current Python `master` branch gets the wrong answer, and that's probably due to [the mercator functions](https://github.com/uber/h3-py/blob/440bc11b2ffb9d42f751073e3e94b87bdbbc2aa2/h3/h3.py#L279-L286). If we just remove those, I expect that the `master` branch would agree with everything else.

**Comment by nrabinowitz** [comment]
Closing, as it seems like core lib implementation is correct.
