### ISSUE TITLE
Non-unique "valid" H3Index representations

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#297]
You can get some weird results by messing with the "reserved" bits in an H3Index. They seem to be ignored by most functions, so by changing them, you can get a **different** H3Index (in that the `uint64` values do not evaluate as equal, even though the correspond to the same H3 cell.

For example,

```python
def poison(h):
    'Set bits (0,5,6,7) to 1'
    ...

h = h3.geo_to_h3(0,0,9)
p = poison(h)

print('', h)
print(p)
```
returns
```
 89754e64993ffff
8f9754e64993ffff
```

Note that `h3.h3_is_valid(p) is True` and `p != h`. However, despite this lack of equality, they correspond to the same hex:
- `h3.h3_get_resolution(h) == h3.h3_get_resolution(p)`
- `h3.h3_to_geo(h) == h3.h3_to_geo(p)`

Note that the "poisoning" seems to carry through when using some common functions:

```python
print('', h3.h3_to_parent(h))
print(h3.h3_to_parent(p))
```
returns
```
 88754e6499fffff
8f8754e6499fffff
```

Even if all functions worked with these "poisoned" hexes, I think we would still have a problem: this breaks a user's expectation that `h1 != h2` would imply that `h1` and `h2` are different hexagons.

However, the "poisoning" does indeed seem to break some functions. For example, for normal hexes, we see the expected `compact` behavior:

```python
>>> hexes = h3.k_ring(h, 4)
>>> len(hexes)
61
>>> len(h3.compact(hexes))
31
```

However, after "poisoning" the same set of hexagons, compact doesn't seem to reduce the size of the hexagon set:

```python
>>> len(h3.compact(map(poison, hexes)))
61
```

Should we change the definition of a "valid" H3Index to be that the "reserved" bits must be zero?

**Comment by dfellis** [comment]
I definitely agree that you've found a bug in h3IsValid. I don't think the other C functions should validate the inputs, though. The bindings could have a slower safe mode that calls it for each bound method, but if the user has prevalidated data in a database letting them reduce the runtime of their loop is worthwhile.

**Comment by ajfriend** [comment]
So does everyone agree that for an H3Index to be valid, its "reserved" bits should all be 0?

If so, I guess the next steps would be to add a test for that in both `h3IsValid` (hexagons and pentagons) and `h3UnidirectionalEdgeIsValid` (unidirectional edges).

**Comment by isaacbrodsky** [comment]
> So does everyone agree that for an H3Index to be valid, its "reserved" bits should all be 0?
> 
> If so, I guess the next steps would be to add a test for that in both `h3IsValid` (hexagons and pentagons) and `h3UnidirectionalEdgeIsValid` (unidirectional edges).

Yes, I agree with this.

**Comment by sahrk** [comment]
> > So does everyone agree that for an H3Index to be valid, its "reserved" bits should all be 0?
> > If so, I guess the next steps would be to add a test for that in both `h3IsValid` (hexagons and pentagons) and `h3UnidirectionalEdgeIsValid` (unidirectional edges).
> 
> Yes, I agree with this.

Me too.

**Comment by nrabinowitz** [comment]
> So does everyone agree that for an H3Index to be valid, its "reserved" bits should all be 0?
> 
> If so, I guess the next steps would be to add a test for that in both `h3IsValid` (hexagons and pentagons) and `h3UnidirectionalEdgeIsValid` (unidirectional edges).

Late to the party, but yes (for H3 cells). Note that unidirectional edge validation _does_ check reserved bits, because they're used in that mode.

**Comment by ajfriend** [comment]
> Late to the party, but yes (for H3 cells). Note that unidirectional edge validation _does_ check reserved bits, because they're used in that mode.

In addition to the 3 reserved bits, don't we also need to require that the first (0th) bit is also zero?

That is, we check that the 3 reserved bits are zero just for the cell case, but we need to ensure the 0th bit is zero for **both** cells and edges?

**Comment by dfellis** [comment]
> > Late to the party, but yes (for H3 cells). Note that unidirectional edge validation _does_ check reserved bits, because they're used in that mode.
> 
> In addition to the 3 reserved bits, don't we also need to require that the first (0th) bit is also zero?
> 
> That is, we check that the 3 reserved bits are zero just for the cell case, but we need to ensure the 0th bit is zero for **both** cells and edges?

That's right, but also @isaacbrodsky 's PR on this does handle that correctly, as you've stated.
