### ISSUE TITLE
Where do we document functions in API?

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#306]
Should we come up with a standard place for documenting the user-facing functions in the API?

It seems like we currently have documentation in both `h3api.h` and in the `.c` files. If these disagree, for example, which should a user believe? Should we agree on a single place for this documentation, maybe *just* the `h3api.h` header?

**Comment by isaacbrodsky** [comment]
Neither of these are what builds the documentation website, which pulls from a different description of the functions in the docs directory. If we make a single place for documentation I'd want it to feed into that as well.

**Comment by ajfriend** [comment]
I wonder if we could automate that? Does the project still use doxygen? I see it referenced in the source code, but I can't tell if we're actually using it to build documentation?

I wonder if we could set things up so that the documentation website builds from doxygen comments in `h3api.h`?
