### ISSUE TITLE
Polyfill returning all intersecting hexagons, expansion of polygon factor.

### ISSUE THREAD

**Issue by rustyconover** [uber/h3#331]
I'm attempting to have polyfill return all hexagons intersected rather than just those hexagon's that have a  center contained in the passed polygon.  

It's been suggested that expanding the polygon by the average edge length of a hexagon at the target resolution is sufficient to ensure that the polygon is covered by polyfill.  I've found that this isn't the case at various resolutions.

Please see this notebook:

https://observablehq.com/@rustyconover/ensuring-h3-polyfill-returns-all-hexagons-for-a-polygon

It seems that resolution 5 and expanding the polygon by the average hexagon edge length polyfill fails to find any intersecting hexagons.

By expanding by a factor of ~1.5 to 2 times the average hexagon length it seems that at all resolutions the polygon is completely covered.  Is there a better procedure to follow for having polyfill return all intersecting hexagons?

**Comment by dfellis** [comment]
[See my answer here.](https://github.com/uber/h3-java/issues/41#issuecomment-613216358)

**Comment by rustyconover** [comment]
@dfellis Thats a perfect answer, thank you!
