### ISSUE TITLE
Add Windows and Mac OS X CI Support

### ISSUE THREAD

**Issue by dfellis** [uber/h3#34]
A few pull requests (especially those by @isaachier ) have been blocked because the change breaks compiling on Windows, but there's no obvious way to be sure of this right now, [since Travis CI doesn't support Windows](https://docs.travis-ci.com/user/multi-os/) (but does support OS X).

It appears that it might make sense to use [Microsoft's free Visual Studio Team Services Continuous Integration](https://www.visualstudio.com/team-services/continuous-integration/) for Windows support. There are instructions for setting up both [gcc-based](https://docs.microsoft.com/en-us/vsts/build-release/apps/c-cpp/gcc?view=vsts&tabs=github) and [visual studio-based](https://docs.microsoft.com/en-us/vsts/build-release/apps/windows/cpp?view=vsts&tabs=github) testing.

Microsoft's CI solution supposedly also supports Linux testing, but not OS X testing, and I also couldn't find anything about code coverage reporting, so I think it would still be required to keep Travis CI (and turn on OS X testing, ideally), but [a second testing integration and badge](https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github?view=vsts#create-a-vsts-build-status-with-a-github-readme-file) could be added for the runs on Windows.

Again, this is something that I would like to help on, but most likely Uber would want to own the Microsoft CI account.

I think I can do the OS X integration, however, if we want to split this into two tasks.

**Comment by isaachier** [comment]
I have a fix for Windows. You can see the appveyor.yml here: https://github.com/isaachier/h3/blob/appveyor/appveyor.yml. The associated builds are here: https://ci.appveyor.com/project/isaachier/h3.

**Comment by isaacbrodsky** [comment]
I'll let @isaachier submit a PR to add Windows CI. Let me know if you'd like me to help, or to work on that.

I think the OSX test part is pretty simple, so I can make a quick PR for that.

**Comment by isaachier** [comment]
Yes I'd love to. Probably early tomorrow. Just wanted to keep the allocation PR clean.
