### ISSUE TITLE
Windows Build Instructions do not generate an sln solution file

### ISSUE THREAD

**Issue by douglasg14b** [uber/h3#353]
Following the instructions from here: https://github.com/uber/h3/blob/master/dev-docs/build_windows.md

Using cmake 3.17.2, and Visual Studio 2019.

Following the instructions to create a build folder and run `cmake ..` from that directory results in that appears to be cmake output, but no solution file as the instructions suggest.

If I use the cmake GUI, select the source (/h3-3.6.3/) & output directory (/h3-3.6.3/build) I get an error:
> Error in configuration process, project files may be invalid

**CMakeOutput.log:**

>The system is: Windows - 10.0.18363 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x86/cl.exe 
Build flags: 
Id flags:  

>The output was:
0
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28805 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

>CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.26.28805.0
Copyright (C) Microsoft Corporation.  All rights reserved.

>/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 

>Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"

>Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"

>The C compiler identification is MSVC, found in "C:/Users/douglas/Programming/3rd Party/h3-3.6.3/build/CMakeFiles/3.17.2/CompilerIdC/CMakeCCompilerId.exe"

>Determining if the C compiler works passed with the following output:
Change Dir: C:/Users/douglas/Programming/3rd Party/h3-3.6.3/build/CMakeFiles/CMakeTmp

>Run Build Command(s):nmake /nologo cmTC_75586\fast && 	"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\nmake.exe"  -f CMakeFiles\cmTC_75586.dir\build.make /nologo -L                  CMakeFiles\cmTC_75586.dir\build

>Building C object CMakeFiles/cmTC_75586.dir/testCCompiler.c.obj

>	C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx86\x86\cl.exe @C:\Users\douglas\AppData\Local\Temp\nmF134.tmp

>testCCompiler.c

>Linking C executable cmTC_75586.exe

>	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_75586.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx86\x86\link.exe /nologo @CMakeFiles\cmTC_75586.dir\objects1.rsp @C:\Users\douglas\AppData\Local\Temp\nmF183.tmp

>Detecting C compiler ABI info compiled with the following output:
>Change Dir: C:/Users/douglas/Programming/3rd Party/h3-3.6.3/build/CMakeFiles/CMakeTmp

>Run Build Command(s):nmake /nologo cmTC_5e5df\fast && 	"C:\Program Files (x86)\Microsoft >Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\nmake.exe"  -f >CMakeFiles\cmTC_5e5df.dir\build.make /nologo -L                  CMakeFiles\cmTC_5e5df.dir\build

>Building C object CMakeFiles/cmTC_5e5df.dir/CMakeCCompilerABI.c.obj

>	C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx86\x86\cl.exe @C:\Users\douglas\AppData\Local\Temp\nmF403.tmp

>CMakeCCompilerABI.c

>Linking C executable cmTC_5e5df.exe

>	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_5e5df.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx86\x86\link.exe /nologo @CMakeFiles\cmTC_5e5df.dir\objects1.rsp @C:\Users\douglas\AppData\Local\Temp\nmF442.tmp

**Comment by isaacbrodsky** [comment]
I can retry this later today, but just to check, are you using the the Tools Command Prompt to run cmake? And could you post the output of running `cmake` itself?

**Comment by douglasg14b** [comment]
I'm using the 
![image](https://user-images.githubusercontent.com/1400380/82847037-b6613000-9ea0-11ea-82da-61ba93866b5e.png)

Ran `cmake` again and this was the output:

```
CMake Warning at CMakeLists.txt:249 (message):
  clang-format was not detected, so automatic source code reformatting is
  disabled


CMake Warning at CMakeLists.txt:261 (message):
  clang-tidy was not detected, so source code linting is disabled


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/douglas/Programming/3rd Party/h3-3.6.3/build
```

**Comment by isaacbrodsky** [comment]
Could you delete the build directory and rerun cmake? When I run from a fresh directory I get output like:

```
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27035.0
-- Check for working C compiler: E:/Dev/Microsoft Visual Studio 2017/VC/Tools/MS
VC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: E:/Dev/Microsoft Visual Studio 2017/VC/Tools/MS
VC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Warning at CMakeLists.txt:273 (message):
  clang-tidy was not detected, so source code linting is disabled


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Dev/h3/build
```

My guess is that CMake is selecting a different generator which is why there is no solution file. You may need to explicitly tell cmake to use Visual Studio 2019 by running "`cmake -G "Visual Studio 16 2019  ..`

What files are generated would also be useful to know if that doesn't solve it, since I'm not seeing an error from CMake.
