### ISSUE TITLE
Run H3-java on CentOS 6.6 Spark Cluster

### ISSUE THREAD

**Issue by ce39906** [uber/h3#357]
@isaacbrodsky 
I'm using H3-java on CentOS 6.6 spark cluster of my company, when I new H3Core instance, the error log shows that Glibc2.14 was not found.
Could you compile a "libh3-java.so" on CentOS 6.6 for me？ That would be very grateful！

**Comment by isaacbrodsky** [comment]
Since this question is specific to using the Java binding and there’s a discussion there, I’ll close this issue so the discussion can continue at one place. Uber/H3-java#62
