### ISSUE TITLE
Are indexes (id's) unique across all levels?

### ISSUE THREAD

**Issue by bilics** [uber/h3#367]
Or are there clashes between levels?

Thanks!

**Comment by isaacbrodsky** [comment]
H3 indexes encode the resolution inside the identifier so there is never a clash.

(for more information:  https://h3geo.org/docs/core-library/h3indexing)

As it happens, for cell indexes, the first hexadecimal digit of the ID is always 8 and the second hexadecimal digit is the resolution. It’s very easy to quickly check which resolution an index represents.

**Comment by bilics** [comment]
Thanks!
