### ISSUE TITLE
Expand naming RFC to consider Vertex mode and undirected edge mode

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#374]
Naming collision/ambiguity concerns, off the top of my head:

- "topological" vertex vs geometric/boundary vertex
    - what naming convention would make this obvious to users?
- directed edge vs (undirected) edge
    - can we use "edge" to mean undirected edge without confusion with directed edge?

@nrabinowitz, just to justify diving into naming, yet again ;)

**Comment by RichardVasquez** [comment]
2 cents here, since things are going to break in 4.0, anyway.

Call a DirectedEdge a Vector, and an undirected edge, just an Edge, or a segment.

**Comment by nrabinowitz** [comment]
We already have a `Vector` internally (used in the internals of `h3ToGeo` and `geoToH3`). I think `Edge` was where we ended up for undirected edges, and `DirectedEdge` has a nice symmetry there. 🤷
