### ISSUE TITLE
Establish H3 equivalent for `NaN`?

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#378]
Maybe somewhat random, but would it make sense to establish a convention for something equivalent to floating point `NaN`, but for H3. Something to indicate missing or invalid data?

This could be useful for when users are processing arrays of H3 indices, and need a way to represent missing data. For example, integer arrays are sometimes cast to float for this purpose, due to the lack of a `NaN` for integers.

This could be as simple as stating that `0` is the "NanH3", which is essentially what we already *implicitly* do in the library. It could be beneficial to establish this convention officially.

I'm not sure this would even require a code change. Maybe just stating this in the docs somewhere as the recommended convention. A code change might be as small as just establishing a constant in the C code.

Thoughts? I don't have a killer use case for this yet, but I thought there was a chance it might be useful in the future.

**Comment by isaacbrodsky** [comment]
We have a constant `H3_INVALID_INDEX` for this purpose:

```
src/h3lib/include/h3Index.h:#define H3_INVALID_INDEX 0
```

We should add to the documentation that unlike other modes, the API specifies the index `0` will not be valid in the future.

**Comment by ajfriend** [comment]
Ah perfect!

However, I'm not sure I understand what you mean here:

> unlike other modes, the API specifies the index `0` will not be valid in the future.

**Comment by dfellis** [comment]
> Ah perfect!
> 
> However, I'm not sure I understand what you mean here:
> 
> > unlike other modes, the API specifies the index `0` will not be valid in the future.

The Index format supports multiple modes, but we currently only use two. We have plans for a third, so that collection of indexes will then become valid. But a full zero set of 64 zeroes will never be a valid H3 Index value (since it's not valid under mode zero, it's impossible for that to change).

**Comment by ajfriend** [comment]
Got it. I do wonder if there's a slight difference between "being invalid" (which, as y'all have sated, may change in the future) and the "NaN of H3".

Uniqueness would be the big one, probably. We wouldn't want folks having the freedom to use just *any* invalid index for NanH3.

The NanH3 might indicate a **little more meaning**: missing data and/or a potential return value for a nonsensically-called function (but error codes might handle that better). Just a regular invalid index would have **a bit less meaning**: just gibberish, and would probably indicate a bug somewhere.

If you buy those arguments, then `H3_INVALID_INDEX` might not be as descriptive of a name as something like `H3_NAN` or `H3_NAI` (not an index?).

**Comment by dfellis** [comment]
I personally like `H3_NULL` since it is literally a 8 [`NUL`](https://theasciicode.com.ar/ascii-control-characters/null-character-ascii-code-0.html) bytes.

**Comment by ajfriend** [comment]
Closed with #379
