### ISSUE TITLE
How to determine if a cell contains the pole

### ISSUE THREAD

**Issue by aaime** [uber/h3#383]
Is there any way to determine if a cell contains the north or south pole?

By looking at the code a bit, it would seem a rule could be "base cell is 4 or 117, and it's a pentagon", which at the base resolution would be "8009" and "80d7" but when I try to map the cells onto a plate carree, those cells do not look like good candidates, e.g. (pentagons in different color to ease their location)):

![image](https://user-images.githubusercontent.com/325433/90640247-0ba6a680-e230-11ea-99fb-66e77aab21ae.png)

**Comment by isaacbrodsky** [comment]
The icosahedron vertices don’t like up with the poles as you noted. For this specific question it seems like you could determine the specific cell by calling geoToH3 with the polar coordinates and the resolution of the grid you want the answer for. (I.e. res 3 if you need to determine if res 3 indexes contain the South Pole)

**Comment by aaime** [comment]
Oh, the answer was pretty obvious, how didn't I think about it! Thanks for showing me the way :+1:
