### ISSUE TITLE
Changes to support h3 builds on FreeBSD

### ISSUE THREAD

**Issue by dcj** [uber/h3#396]
I modified all the shebang lines in the bash scripts to `#!/usr/bin/env bash`

`sudo pkg install bash cmake gmake doxygen lcov # can’t find the others`

And followed the instructions, `make test` returned: 

`100% tests passed, 0 tests failed out of 120
Total Test time (real) = 101.22 sec`

Pull request coming...

**Comment by ajfriend** [comment]
Any chance these changes would address the issue here: https://github.com/uber/h3-py/issues/170

**Comment by isaacbrodsky** [comment]
Closing as these changes have been released in v3.7.1, thanks!
