### ISSUE TITLE
Toolchain file breaks cross compilation

### ISSUE THREAD

**Issue by BenoitDuffez** [uber/h3#419]
If this is used as a dependency of a project that uses a cmake toolchain file, this may not compile. The toolchain file used by h3 is `cmake/toolchain.cmake` and it supersedes the default toolchain file.

I don't know about cmake enough to be able to submit a pull request, but for me the fix was simple: remove `cmake/toolchain.cmake` and make sure my toolchain file has the C99 requirements.

**Comment by isaacbrodsky** [comment]
It looks like in [CMakeLists.txt](https://github.com/uber/h3/blob/master/CMakeLists.txt#L26) the intention is that we provide a default that can be overridden. Does your project set `CMAKE_TOOLCHAIN_FILE` or do you set that when calling `cmake`? It would be very helpful if you could share a smallCMake example that demonstrates this issue.

**Comment by BenoitDuffez** [comment]
I know close to nothing to cmake. Can you explain if this code below is optional or sets something only if it doesn't exist?
```
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/toolchain.cmake"
    CACHE FILEPATH
    "Toolchain to use for building this project")
```

I call the main project compilation with `CMAKE_TOOLCHAIN_FILE` defined, but there are several nested build system calling one another, so the problem might be that the environment variable is not passed.

**Comment by BenoitDuffez** [comment]
I have read the cmake doc and see that `CACHE` means "don't overwrite if user has set it". So you're right, it's exactly what's needed.

Now my problem is that the env variable _is_ set! I don't know if this is a problem related to cmake, to how I invoke cmake, or to this project code.
I did this modification (add commands & logging):

```
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
execute_process(COMMAND bash "-c" "echo CMAKE_TOOLCHAIN=$CMAKE_TOOLCHAIN")
execute_process(COMMAND bash "-c" "echo env=$(env | grep ^CMAKE_TOOLCHAIN)")
message(STATUS "toolchain file = ${CMAKE_TOOLCHAIN_FILE}")
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/toolchain.cmake"
    CACHE FILEPATH
    "Toolchain to use for building this project")
```

The execution result is:
```
===> Verifying dependencies...
===> Compiling h3
-- Using upstream h3 tag v3.6.4 based on local tag v3.6.4-12-g8541da4
-- Configuring done
-- Generating done
-- Build files have been written to: /miner/_build/default/lib/h3/_build/c_src
make[1]: Entering directory '/miner/_build/default/lib/h3/_build/c_src'
make[2]: Entering directory '/miner/_build/default/lib/h3/_build/c_src'
make[3]: Entering directory '/miner/_build/default/lib/h3/_build/c_src'
make[3]: Leaving directory '/miner/_build/default/lib/h3/_build/c_src'
make[3]: Entering directory '/miner/_build/default/lib/h3/_build/c_src'
[ 10%] Performing update step for 'external-h3'
[ 20%] Performing configure step for 'external-h3'
CMAKE_TOOLCHAIN=
env=CMAKE_TOOLCHAIN_FILE=/toolchain/cmake-toolchain
-- toolchain file = /miner/_build/default/lib/h3/_build/c_src/external-h3/src/external-h3/cmake/toolchain.cmake
```
As you can see, the env contains the appropriate toolchain file, but cmake seems to be unable to read the variable from env? Or perhaps the `${VAR}` syntax isn't supposed to read env vars (but `$ENV{VAR}` is?).

Again this perhaps comes from my lack of knowledge of cmake. I appreciate your time helping me.

**Comment by isaacbrodsky** [comment]
How do you invoke the CMake process to build H3? From the command line I would expect it to look something like `cmake h3 -DCMAKE_TOOLCHAIN_FILE=...` I am not sure if CMake would actually read the environment variables since it doesn't seem to be listed here: https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html I believe you will need to more explicitly tell CMake where to find the toolchain file.

**Comment by BenoitDuffez** [comment]
I invoke with `cmake --build _build/c_src -- install` but no matter where I put the `-DCMAKE_TOOLCHAIN_FILE`, cmake refuses to start. Example:

```
# cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE --build _build/c_src -- install
CMake Error: The source directory "/miner/_build/default/lib/h3/install" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by BenoitDuffez** [comment]
I wish cmake would use the environment variable like this proposition: https://gitlab.kitware.com/cmake/cmake/-/issues/19842

**Comment by BenoitDuffez** [comment]
OK I found out. My project (not mine, the one I'm building) is in Erlang and invokes a wrapper that includes h3.
This wrapper compiles with:

```
cmake -B_build/c_src -Hc_src
cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE --build _build/c_src -- install
```

The first step is able to receive `-DCMAKE_TOOLCHAIN_FILE`. I'll work on that, thanks for the hint.

**Comment by BenoitDuffez** [comment]
OK I found out the real issue, cmake is invoked twice (nested) and the first didn't pass the option to the second.
=> https://github.com/helium/erlang-h3/pull/26

Thanks for your help!!!
