### ISSUE TITLE
naming "k-ring"

### ISSUE THREAD

**Issue by sahrk** [uber/h3#42]
Internally H3 uses an IJK hex coordinate system, where each hex coordinate has a k-component. So it seems confusing to me to use "k-ring" to refer to an unrelated concept. Have you considered changing to a different label for that concept?

I have mostly dealt with the similar concept of the ring of hexagons at exactly the same metric distance from a central cell. I used to call this an "r-ring", for "radius". But r is too convenient for grid resolution, so I switched to "d-ring", for distance. Lately I've been moving towards referring to grid precision, rather than resolution, as I think that more precisely expresses the situation from the standpoint of the data structure. Then p for "precision" leaves r available for "r-ring". But alas I was still on the fence on resolution/precision when I worked on H3, so I used resolution in naming. But I offer up those alternatives for k-ring; I'd synchronize my terminology with H3 going forward if you chose something other than k-ring.

**Comment by isaacbrodsky** [comment]
Could "radius ring" be simplified to "ring" (hollow ring) and "rings" (existing k-ring)? In function parameters, `k` could be replaced with `radius`.

If we do rename things, we should clear up the naming of the `kRing`, `hexRing`, and `hexRange` functions. `hexRing` is the only one of those that produces a hollow ring.

**Comment by dfellis** [comment]
I will note that this would be a semver major version change. Would recommend keeping the old names as aliases and then dropping them when "enough" breaking changes have been proposed, or we'll outpace Chrome's versioning.

**Comment by sahrk** [comment]
I had to read the documentation several times to clarify the differences between the different “Neighbor traversal functions”. First note that normally the hex ring at `k` distance from a central hex should have sides of length `k`. Assuming that’s the semantics of `hexRing` then it might make sense to align the description in the documentation with the other functions, which all are defined in terms of distance from the center.

@isaacbrodsky I’m OK with your suggestion of “ring” for the hollow ring (current `hexRing`), but I think “rings” is a better fit for `hexRange` than `kRing`, since it looks like `hexRange` is ordered by rings of increasing distance, while `kRing` doesn’t guarantee ring-ordering in the output. For `kRing` I’d suggest one of the following: `region`, `vicinity`, `neighborhood`, `zone`, or `sphere`.

So we could, for example, use `ring`, `rings`, and `neighborhood` for `hexRing`, `hexRange`, and `kRing` respectively. But I guess I still feel like it would tie the three concepts together better if we added a common prefix, like the previously mentioned `r-` or `d-`; e.g., `d-ring`, `d-rings`, and `d-neighborhood`.

I’m a little uncomfortable that `ring` vs. `rings` might not have enough differentiation and might still lead to confusion, but the best I’m coming up with is `sectors` or `zones`, neither of which imply the ring concept.

**Comment by ajfriend** [comment]
I'd vote for the following function names:

- `ring`: "hollow" ring of cells distance `== k` from an origin cell
- `disk`: "solid" disk of cells distance `<= k` from an origin cell
- `rings`: a collection of `ring`s indexed by grid distance from the origin cell

**Comment by ajfriend** [comment]
I'll close this as it seems we've addressed these with #308.

@sahrk, let me know if you disagree, can we can re-open!
