### ISSUE TITLE
Minor error in testH3Distance.c?

### ISSUE THREAD

**Issue by RichardVasquez** [uber/h3#424]
The last test named h3DistanceEdge() performs the same test twice at the end, though it looks like the very last assert should be flipped around.

```
        t_assert(H3_EXPORT(h3Distance)(edge, dest) == 1,
                 "edge has distance to destination");
        t_assert(H3_EXPORT(h3Distance)(edge, dest) == 1,
                 "destination has distance to edge");
```

Replacing it with ```t_assert(H3_EXPORT(h3Distance)(dest, edge) == 1,``` should fix it.

I wasn't too sure if a PR for this one line was merited.

**Comment by nrabinowitz** [comment]
Thanks for logging! I'll submit a quick fix.
