### ISSUE TITLE
Pre-generated hex indices?

### ISSUE THREAD

**Issue by maphew** [uber/h3#428]
Where might one be able to download pre-generated h3 index grids? https://h3geo.org/docs/core-library/overview says they can be built with `make kml`, but I don't have a build environment. I want to use the hex grids in GIS software that doesn't have H3 plugins. There are probably others like me also.

**Comment by isaacbrodsky** [comment]
What resolution of grid do you need? The main impediment to making grid shapefiles available is the size of the file (after about resolution 4 or so) becomes very large.

If you need a certain area of interest at a higher resolution there are ways of generating partial shapefiles. The way to do this might depend on your operating system or if you have any programming environments readily available.

**Comment by maphew** [comment]
I'm primarily interested in levels 3 to 6 inclusive, and my area of interest is approx -142W, 59N to -122W, 70N. I'm familiar with python but not jupyter notebooks. 

I've been able to [adapt][0] some [code][1] `h3-py` in Qgis to get partway there by using the centroids of a rectangular grid poly layer, but the resulting h3 polygons are not seamless. Following a suggestion on the h3 Slack channel I found after opening this issue I'm attempting to further adapt the script to use `h3.polyfill` instead. 

It's slow going for me -- I started this 3 days ago and am losing my motivation for learning -- which is why decided to ask if I can just download them from somewhere. ;-)

![image](https://user-images.githubusercontent.com/486200/106503882-10c47e80-647b-11eb-9f6b-b4370891f4ef.png)

[0]: https://gist.github.com/maphew/2ced5176c82aa486c70ca981015e08cb
[1]: https://github.com/ThomasG77/30DayMapChallenge/blob/master/day4_hexagons/data/h3-processing.py

**Comment by maphew** [comment]
With help from the h3 slack I've got my script to the point where it does what I need: https://github.com/maphew/code/tree/master/gis/qgis. I guess the answer to the opening question is: no, they're not available pre-generated, and it's not really a good idea anyway. The files are too big to be practical.

**Comment by maphew** [comment]
To get an idea of how much space is needed for a given area at interest, generate hexes at small scale, say level 5. Measure the storage size of the resultant files. Multiply by 7 to get the size of the next level, and then by 7 again for the next level, and so on to Level 15.

A 1x1 degree area at L5 in shapefile format is 12 KiB. Therefore the subsequent levels are:

    L6  :  84
    L7  :  588
    L8  :  4,116
    L9  : 28,812
    L10 : 201,684 \* 
    L11 : 1,411,788
    L12 : 9,882,516 \**
    L13 : 69,177,612
    L14 : 484,243,284
    L15 : 3,389,702,988

\* measured at 196 MB. 
\** measured at 9.2 GB 

The initial 12 KB is rounded up from 11.x, so each subsequent estimate is overly large. So level 15 actual storage is probably closer to 3 TB than 3.4 TB.
