### ISSUE TITLE
Move some user-facing definitions from `h3Index.h` to `h3api.h`?

### ISSUE THREAD

**Issue by ajfriend** [uber/h3#431]
Would it make sense to move the `H3_NULL` definition and the `compact` return code definitions from `h3index.h` to `h3api.h`? This would make them more visible/accessible to the user.

https://github.com/uber/h3/blob/b04c78fa08adbd6857aa6f4b2a0f8e08a4ce2ead/src/h3lib/include/h3Index.h#L167-L180

Since https://github.com/uber/h3/blob/master/dev-docs/RFCs/v4.0.0/error-handling-rfc.md is in progress, maybe we'd really only need to consider moving `H3_NULL`?

**Comment by isaacbrodsky** [comment]
Since the define is part of our public API, I think it makes sense for it to be in the public API file.

**Comment by ajfriend** [comment]
`H3_NULL` got done in #413. Still need to move over the compact return codes.

**Comment by ajfriend** [comment]
Done with #465
