### ISSUE TITLE
h3geo.org is not resolving

### ISSUE THREAD

**Issue by riazarbi** [uber/h3#447]
When I visit https://www.h3geo.org, I get a security warning that the certificate is only valid for github.com. When I click 'proceed', I am taken to a github-branded 404 error.

![image](https://user-images.githubusercontent.com/13433911/114544850-7b542080-9c5b-11eb-908a-743769973e4d.png)

**Comment by isaacbrodsky** [comment]
We're currently working on an issue with the site and hope to have it back up soon.

Unfortunately a Github Pages issue caused it to be disassociated from our repo.

**Comment by isaacbrodsky** [comment]
The issue with Github pages was resolved and the site should be back up now. Previous links should work, but the site is updated with a new API reference and more.
