### ISSUE TITLE
Question: Get resulting hex data from Hexagon layer

### ISSUE THREAD

**Issue by Portur** [uber/h3#449]
Hi,

I've been using the `deck.HexagonLayer` with great success. Here is a screenshot of how we display http requests on a weekly basis:
![image](https://user-images.githubusercontent.com/24350810/114831094-47990800-9dcd-11eb-804a-41d19a0439de.png)

Currently its an array of weeks `data = new Array(51).fill(randomLatitiude(), randomLongitude())` and we simply recreate the layer based on what week we want to show, like `data[weekNumber]`

This is great however I'd like to show _change_ based on the total average. An example result would be something like this Google Calendar chart, but using the Hexagon layer, showing percentage difference from the average:
![image](https://user-images.githubusercontent.com/24350810/114831066-3e0fa000-9dcd-11eb-879c-79c823b1277c.png)

The way this is calculated is simply getting the average per day and assigning the percentage difference to the value for each day, either +% or -%.

With the hexagon layer its a bit trickier, you'll need to get an average per `weekNumber` however each value assinged to the `hex_id` should be an average value, not a count. Now I can't find a way to extract the resulting data when a layer is created `new deck.HexagonLayer({ id: 'hexgaon-log-layer',  data: hex_locations[week], ...})` which would allow me to do it manually.

Is my only option to recreate the data per `hex_id` and then create the layer?
Or is there an easier to way to either extract the resulting data or set some options to do this?

**Comment by Portur** [comment]
Sorry, only now posted on [StackOverflow](https://stackoverflow.com/questions/67105371/get-resulting-hex-data-from-hexagon-layer-in-h3)

**Comment by dfellis** [comment]
I'll note that Deck.gl's [HexagonLayer](https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer) is a lat, lng aligned hex binning algorithm. What you want is [H3 HexagonLayer](https://deck.gl/docs/api-reference/geo-layers/h3-hexagon-layer) instead.

**Comment by Portur** [comment]
Thank you, I did not know that.
