### ISSUE TITLE
AttributeError: module 'h3' has no attribute 'h3_to_parent'

### ISSUE THREAD

**Issue by isthegoal** [uber/h3#457]
when i use pyspark to deal data
![image](https://user-images.githubusercontent.com/28563573/116399072-17d11200-a85b-11eb-9b23-ba1be195b67e.png)

It happen following error。
![image](https://user-images.githubusercontent.com/28563573/116398823-cb85d200-a85a-11eb-8283-6aa69e6d5e6d.png)
Can't h3 be used in pyspark udf？

**Comment by nrabinowitz** [comment]
This should probably be posted to https://github.com/uber/h3-py - cc @ajfriend

**Comment by isthegoal** [comment]
> This should probably be posted to https://github.com/uber/h3-py - cc @ajfriend

thanks very much!

**Comment by ajfriend** [comment]
I'll close this out to move the discussion to https://github.com/uber/h3-py/issues/186

I'm not familiar with PySpark internals, so we probably need to find someone who could help shed some light on what'd we'd need to change in `h3-py` (if that is the issue here).
