### ISSUE TITLE
Possible vulnarability in outdated css-what, dns-packet

### ISSUE THREAD

**Issue by michaelbrichko** [uber/h3#484]
**Description:**
The css-what package before 5.0.1 for Node.js does not ensure that attribute parsing has Linear Time Complexity relative to the size of the input.

This affects the package dns-packet before versions 1.3.2 and 5.2.2. It creates buffers with allocUnsafe and does not always fill them before forming network packets. This can expose internal application memory over unencrypted network when querying crafted invalid domain names.

**Needed fix:**
Upgrade css-what from 3.4.2 to 5.0.1 to fix the vulnerability.
Upgrade css-what from 2.1.3 to 5.0.1 to fix the vulnerability.
Upgrade dns-packet from 1.3.1 to 1.3.2 to fix the vulnerability.

**Comment by isaacbrodsky** [comment]
Thanks for the note. I created #485 to bump the dependencies on our static website.

**Comment by michaelbrichko** [comment]
Thank you !
