### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [uber/h3#50]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

I used the colours of your website.

Greetings
![h3](https://user-images.githubusercontent.com/34600369/39478352-1c178966-4d5a-11e8-9390-685760bee1ad.png)

**Comment by nrabinowitz** [comment]
Thanks for your submission! We actually have folks here at Uber working on a potential logo for the project now, so we'll have to pass on adopting this, but thanks in any case!
