### ISSUE TITLE
Orientations

### ISSUE THREAD

**Issue by r-barnes** [uber/h3#510]
The [overview](https://github.com/uber/h3/blob/master/website/docs/core-library/overview.md) document states:
> The icosahedron is fixed relative to the sphere using a Dymaxion orientation (due to R. Buckminster Fuller). This is the only known orientation of a spherical icosahedron that places all 12 icosahedron vertices in the ocean.

[Some work I published in 2019](https://richard.science/sci/2019_barnes_dgg_published.pdf) shows (Table 2) that there are a number of orientations which place all the icosahedron's vertices in the ocean and that these can be tuned to minimize or maximize quantities such as the total iscosahedral edge length which overlaps landmasses. I've adapted the table below:
```
Polyhedron          Vertices          Optimized     Optimized Coordinates of 
                    overlapping land  Quanity       Value     primary vertex
Regular Icosahedron 0                 max(avg dist)  717.62   25.4981 −139.4880 58.2846
Regular Icosahedron 0                 min(avg dist)  223.73   24.9672   67.4845 57.7353
Regular Icosahedron 0                 min(edge)     2456.00   18.9602  −61.1569 21.7798
Regular Icosahedron 0                 max(edge)     3147.00   55.0965  140.7330 15.5157
Regular Icosahedron 8                 min(avg dist)   44.18   34.5965  −85.5585 34.8110
Regular Icosahedron 8                 max(avg dist)  407.80   21.8598  −14.1591 47.9955
Regular Icosahedron 8                 min(edge)     3007.00   37.3477  −85.0918 33.5892
Regular Icosahedron 8                 max(edge)     3576.00   79.1494  −54.0237 49.0449
```

**Comment by nrabinowitz** [comment]
Thanks for the info! We can update the docs, but note that we can't re-orient the icosahedron without invalidating all previous H3 indexes, which need to remain stable.

**Comment by sahrk** [comment]
When I wrote that sentence in the docs (in 2016) the dymaxion was the only such orientation known, since Richard hadn’t yet done his research. The easiest fix might be to just make the sentence read “This orientation of a spherical icosahedron places all…”.

@r-barnes we should make your orientation a preset in DGGRID.

**Comment by nrabinowitz** [comment]
@dfellis notes that we could, technically, have another mode that would use other icosahedron orientations. Pole-aligned orientations have also been requested by some users. But obviously all the indexes would be different in this alternate mode.

**Comment by isaacbrodsky** [comment]
I added a change for this to #513. My proposed change is:

> The icosahedron is fixed relative to the sphere using a *Dymaxion* orientation (due to R. Buckminster Fuller). This orientation of a spherical icosahedron places all 12 icosahedron vertices in the ocean. (At the time of H3's development, this was the only known orientation with this property. [Others have since been found](https://richard.science/sci/2019_barnes_dgg_published.pdf).)

Thanks for letting us know about your research!

**Comment by r-barnes** [comment]
Thanks! :-)
