### ISSUE TITLE
Citation for reference in academic work

### ISSUE THREAD

**Issue by ckrapu** [uber/h3#522]
I've been using H3 for a research project and would like to cite it appropriately. Is there any precedent or desired citation for this? Also, would it be more appropriate to use an organizational author or 1+ individual authors? I currently have the following as my best guess for a citation.

H3: A Hexagonal Hierarchical Geospatial Indexing System (version 3.7.2). Uber, 2021. https://github.com/uber/h3.

**Comment by dfellis** [comment]
If you wish to cite the underlying theory behind H3, I'd recommend citing Dr. Sahr's (@sahrk) work referenced here: https://h3geo.org/docs/core-library/overview

If you're citing H3 specifically for reasons beyond Dymaxion-oriented, Gnomonic-projected icosahedron with 122 base cells and aperture 7 subdivisions (the indexing format, various transforming functions, bindings into popular languages, etc) then I think your citation is fine, though it may make sense to replace the URL with https://h3geo.org

**Comment by ckrapu** [comment]
Got it. Thanks for the advice about the URL!
