### ISSUE TITLE
Move GeoJSON normalization logic into core C lib

### ISSUE THREAD

**Issue by nrabinowitz** [uber/h3#53]
At present, the `h3SetToLinkedGeo` function produces a single polygon with multiple outer loops, without a guaranteed order. The correct GeoJSON output should only have one outer loop per polygon, and the order of loops within each polygon should be `outer, hole, hole, ...`.

The logic for this is included in the (as yet unpublished) JS and Python bindings, but should be moved into the core C lib. The API of `h3SetToLinkedGeo` would not change, so this might not require a new API function, but its correctness guarantees would improve.

**Comment by alexkokorin2** [comment]
@isaacbrodsky any update on this?

**Comment by alexkokorin2** [comment]
Could you give me a hint/source how to create (at least) temporary fix for this?

**Comment by alexkokorin2** [comment]
@nrabinowitz @isaacbrodsky ping about temporary fix.

**Comment by nrabinowitz** [comment]
@alexkokorin2 The basic algorithm looks like:

- Loop through all polygons
  - If the polygon winds counter-clockwise, it's an outer loop, put it into an array of outer loops
  - If the polygon winds clockwise, it's an inner loop (hole). Put it in a temp array of inner loops
- Loop through all inner loops
  - Take the first point. 
  - Loop through all outer loops. If the point is inside the outer loop, allocate the hole to that polygon.
- Return the array of outer loops.

This doesn't deal with nested donuts, but otherwise should work. I'm going to be releasing a JavaScript GeoJSON lib shortly, and will probably include a JS version of this algorithm in that lib until this issue is resolved in the core library.
