### ISSUE TITLE
DGGRID copyright reference in project readme.md file

### ISSUE THREAD

**Issue by KRyden** [uber/h3#531]
The h3 project readme.md file includes a "Legal and Licensing" reference to:

DGGRID Copyright (c) 2015 Southern Oregon University

This software is licensed under an AGPL license - it is unclear why this reference is included here.  I am not seeing any other reference to it, and the H3 software is licensed under Apache.  Can somebody please provide some clarification as to why the DGGRID reference is included and if it has any relevance to the H3 licensing?

**Comment by sahrk** [comment]
A couple of the low-level functions in H3 were copied/adapted from DGGRID in 2016, when the license for DGGRID had no limitations. The license for DGGRID changed to AGPL in 2019.

**Comment by KRyden** [comment]
Thank you - this is exactly the information I needed to clarify the citation.  Much appreciated.
