### ISSUE TITLE
Can I use another coordinate system？

### ISSUE THREAD

**Issue by changechenhao** [uber/h3#543]
I know document said:`The hexagonal grid system is created on the planar faces of a sphere-circumscribed icosahedron, and the grid cells are then projected to the surface of the sphere using an inverse face-centered polyhedral gnomonic projection. The coordinate reference system (CRS) is spherical coordinates with the WGS84/EPSG:4326 authalic radius. It is common to use WGS84 CRS data with the H3 library.`

Can I use another coordinate system？for example：EPSG:3857，Will it have any other impact？

**Comment by nrabinowitz** [comment]
All input and output coordinates are expected to be in WGS84 latitude/longitude coordinates, based on a spherical model of the Earth. If you wanted to use another coordinate system, you'd need to transform input/output yourself - H3 doesn't provide any affordance for selecting another coordinate system within the library. Internally, H3 uses a spherical model and radian coordinates; the only parts of the library that consider an Earth-centric model (i.e. that use the Earth radius) are area and distance functions.

**Comment by changechenhao** [comment]
> 
Thank you.
