### ISSUE TITLE
h3togeo is not the centroid of the cell

### ISSUE THREAD

**Issue by francois-baptiste** [uber/h3#572]
In the API documentation (https://h3geo.org/docs/api/indexing/#h3togeo) `h3togeo` is described as returning the index centroid.
However due to distortion of some cells, this is not entirely exact if we consider the standard definition of the centroid (as the projected center of the uniformly distributed mass of the cell index).

`h3togeo` should be better defined as the convergence point of the central child cell when the resolution goes finer.

For instance if I calculate the centroid of the index `85283473fffffff` (resolution 5), I get the point `POINT(-121.976343311047 37.345768562411)` while the `h3togeo` function returns the point `POINT(-121.976375972551 37.34576935375)`

The first point can be mapped to index "8f2834700000036" at resolution 15, while the second is mapped to "8f2834700000000" which is the central child of the initial cell.

**Comment by sahrk** [comment]
Yes, that document is incorrect. The returned point is actually the center of the hexagon in the H3 projection space, inversely projected to the sphere.

**Comment by isaacbrodsky** [comment]
Thanks for pointing this out and to @sahrk for confirming the correct explanation. I took a shot at updating the docs in #574 to fix this.

**Comment by dfellis** [comment]
I am somewhat confused by this discussion.

On each icosahedron face the hexagons are uniform in size and the centroid of the hexagon *is* the exact center of the hexagon. This icosahedron is then projected back onto the Earth with the gnomonic projection system, so the centroid being shifted would be due to that projection and will vary based on where on the icosahedron it is: the central hexagon of each icosahedron *should* have a centroid that matches reality, while the hexagons closest to the vertices of the icosahedron faces should have the greatest discrepancy (and greatest distortion from a Regular hexagon).

So perhaps it would be best to state the centerpoint as reported by `h3ToGeo`/`cellToLatLng` is the center of the hexagon in grid space, and will drift versus the centroid of the hexagon on Earth due to distortion from the gnomonic projection within the icosahedron face it resides on and its distance from the center of the icosahedron face?

**Comment by sahrkm** [comment]
> On each icosahedron face the hexagons are uniform in size and the centroid of the hexagon _is_ the exact center of the hexagon. This icosahedron is then projected back onto the Earth with the gnomonic projection system, so the centroid being shifted would be due to that projection and will vary based on where on the icosahedron it is: the central hexagon of each icosahedron _should_ have a centroid that matches reality, while the hexagons closest to the vertices of the icosahedron faces should have the greatest discrepancy (and greatest distortion from a Regular hexagon.

That is a very nice description of what is occurring. Only the center hex on each icosahedron face (and I believe the pentagons) are regular spherical polygons when projected to the sphere, and the center/centroid of each of these (and only these) will transform to/from the exact center point of those cells on the planar icosahedron faces.

> So perhaps it would be best to state the centerpoint as reported by `h3ToGeo`/`cellToLatLng` is the center of the hexagon in grid space, and will drift versus the centroid of the hexagon on Earth due to distortion from the gnomonic projection within the icosahedron face it resides on and its distance from the center of the icosahedron face?

I like that. I was trying to avoid a list of equivalent geometric constructions. But explaining it that way gives the user just what they need to know.

**Comment by sahrk** [comment]
> On each icosahedron face the hexagons are uniform in size and the centroid of the hexagon _is_ the exact center of the hexagon. This icosahedron is then projected back onto the Earth with the gnomonic projection system, so the centroid being shifted would be due to that projection and will vary based on where on the icosahedron it is: the central hexagon of each icosahedron _should_ have a centroid that matches reality, while the hexagons closest to the vertices of the icosahedron faces should have the greatest discrepancy (and greatest distortion from a Regular hexagon).

That is a very nice description of what is occurring. Only the center hex on each icosahedron face (and I believe the pentagons) are regular spherical polygons when projected to the sphere, and the center/centroid of each of these (and only these) will transform to/from the exact center point of those cells on the planar icosahedron faces.

> So perhaps it would be best to state the centerpoint as reported by `h3ToGeo`/`cellToLatLng` is the center of the hexagon in grid space, and will drift versus the centroid of the hexagon on Earth due to distortion from the gnomonic projection within the icosahedron face it resides on and its distance from the center of the icosahedron face?

I like that. I was trying to avoid a list of equivalent geometric constructions. But explaining it that way gives the user just what they need to know.

**Comment by francois-baptiste** [comment]
Thank you for your support @sahrk @isaacbrodsky @dfellis! Glad to see you are so responsive to the H3 community!
