### ISSUE TITLE
How do I group hexagons with the same color?

### ISSUE THREAD

**Issue by alexkokorin2** [uber/h3#59]
Let's say I wanna create something similar to movements.uber ([pic](https://imgur.com/a/4fyRhqZ)).

I.e. the task is to return a group of points for every connected polygon (connected means 'hexagons have the same color').

Originally I use polyfill to extract list<long> hexagonId and then extract create
`Hexagon { long hexagonId, Color color, List<Vector2D> vertices } -> List<Hexagon> hexagons`

My current solution is to group these hexagons by `color` and then we kinda want to create a convex hull for a whole group of hexagons but the problem is that we can have multiple connected components. Is there a better option (some builtin methods) than to run bfs-like algorithms using a `kring(distance=1)` to separate these components?

**Comment by isaacbrodsky** [comment]
I think the function [h3SetToLinkedGeo](https://uber.github.io/h3/#/documentation/api-reference/regions) (in Java, h3SetToMultiPolygon) would be what you need. This function takes a collection of hexagon indexes, and returns the outlines (hulls) of those hexagons.
