### ISSUE TITLE
glibc in wrong version: changes from 3.6.3 to 3.7.1

### ISSUE THREAD

**Issue by geoHeil** [uber/h3#590]
I face a similar problem as in https://github.com/uber/h3/issues/493

But observe that 3.6.3 works fine - but 3.7.1 fails due to glibc missing for version 2.29.

So far I could not find the changes in H3 which lead to now requires the updated library. Can you explain what changed between these versions?

**Comment by isaacbrodsky** [comment]
@geoHeil is this also using H3-Java? If so, the cross compiler version has not been pinned which is likely responsible for this issue.

**Comment by geoHeil** [comment]
correct - this is from java.

**Comment by geoHeil** [comment]
https://github.com/uber/h3-java/issues/85 is related

**Comment by isaacbrodsky** [comment]
Should be corrected in v4.0.0.
