### ISSUE TITLE
Create Spatial Index using Neural Network [Feature Request]

### ISSUE THREAD

**Issue by carlosg-m** [uber/h3#606]
Consider a Skip-gram model from NLP.
Apply the same concept to pairs of points in ECEF, instead of Cosine distance use Euclidean distance.
Get extremely accurate multidimensional projection (>2 dimensions) that works for the entire globe. In this case the L2 norm between any two vectors should be approximately equal to the geodesic distance.
Use the projection as base to hash geometries and so on (similar to encoding a sentence by merging the embedding of each word).

The idea here, if possible, would be to project the surface of a manifold into a high dimensional Cartesian plane.

https://carlostgameiro.medium.com/disrupt-spatial-analysis-642eeb360493

**Comment by isaacbrodsky** [comment]
Thanks for contributing this idea. I think exploring it outside of this repository would make the most sense at this point as I don't see it as something we would merge in H3.
