### ISSUE TITLE
Strange behaviour of h3SetToMultiPolygon()

### ISSUE THREAD

**Issue by alexkokorin2** [uber/h3#61]
I used this method in Java: `public List<List<List<Vector2D>>> h3SetToMultiPolygon(Collection<Long> h3, boolean geoJson)`

```
long hexagonId = core.geoToH3(40.7128, 74.0060, 5);
List<Long> hexagonIds = core.kRing(hexagonId, 2);
hexagonIds.removeAll(core.kRing(hexagonId, 1));
hexagonIds.add(hexagonId);
List<List<List<Vector2D>>> polygons = h3Core.h3SetToMultiPolygon(hexagonIds, true);
```

So basically I should get 2 polygons (one is a 'core' hexagon w/o holes, the other is a set of hexagons whose distance from 'core' hexagon is 2 with a hole). Here's what ([pic](https://imgur.com/a/WaHFjLf)) I received instead.

Here you can see the [order](https://imgur.com/a/8bcZcEm) is strange (I did receive only 1 polygon which has 1 outline and 2 holes, and the outline itself is arr[1] (not arr[0])).

What's wrong with my code or this method?

**UPD**: I found this in docs: _At present, if the set of hexagons is not contiguous, this function will return a single polygon with multiple outer loops. The correct GeoJSON output should only have one outer loop per polygon. It appears that most GeoJSON consumers are fine with the first input format, but it's less correct than the second format. The function may be updated to produce multiple polygons in the future._

Could you specify what you meant by **_the first input format, but it's less correct than the second format_**?

**Comment by isaacbrodsky** [comment]
The "first input format" here means putting all outlines and holes in a single polygon. I think the "second format" would be the format you expect, with two polygons, and the outline ordered before the holes. There's an open issue (#53) to change this in the core library.

**Comment by alexkokorin2** [comment]
Thanks, so basically I should wait until #53 get solved ('the 1st format' will be replaced with 'the 2nd one' or there'll be a method to get 'the 2nd format'), right?

**Comment by nrabinowitz** [comment]
Yes - the signature of the method doesn't change, so our intent is to simply output the proper format instead of the current format.
