### ISSUE TITLE
Wrong use of float instead of double?

### ISSUE THREAD

**Issue by slaperche-zenly** [uber/h3#651]
I was strolling around the codebase, and stumbled upon this:

https://github.com/uber/h3/blob/cd87201c1b0c3caf265f402378790b5737529c97/src/h3lib/lib/vec2d.c#L41-L55

Seeing that most, if not all, of the codebase use `double` for calculation, this looks like a mistake/bug to me (the use of `float` for `t`).

Or am I missing something that justify the use of `float` here?

From a quick testing using `cellToBoundary` the precision loss does affect, in some cases, the end result in a way that's above the EPSILON_RAD threshold.

**Comment by nrabinowitz** [comment]
I added some tests based on `cellsToLinkedMultiPolygon`, which currently depends on comparing lat/lng coords from different cells, and I can confirm that changing to `double` causes some tests to pass that fail with `float`. I'll put up a PR now.

**Comment by slaperche-zenly** [comment]
> We had previously done a cleanup pass adjusting types to `double` (mostly from `long double`), which I agree probably should have included this.

There is still a bunch of `long double` "hidden" in the codebase though: floating-point constants suffixed with `L` (e.g. `M_SQRT7`)

IIRC, in C:
- `f` suffix -> `float`
- no suffix -> `double`
- `L` suffix -> `long double`

But maybe it's fine.
The extra-precision probably influence the results whether 80-bit float are available (Intel mainly, with the x87) or not, but less dramatically than the `float` issue here.
