### ISSUE TITLE
Has the description of the file "Polyfill modes RFC" been implemented

### ISSUE THREAD

**Issue by changechenhao** [uber/h3#661]
Document location：https://github.com/uber/h3/blob/master/dev-docs/RFCs/v4.0.0/polyfill-modes-rfc.md
Version：v4.0.0
Question：How to configure flags in Java

**Comment by nrabinowitz** [comment]
The short answer is, not yet. We have added the `options` argument that will allow new modes without a breaking API change, but we haven't implemented different modes yet.

**Comment by changechenhao** [comment]
thank you
