### ISSUE TITLE
Docs: migrating-3.x link to list of functions

### ISSUE THREAD

**Issue by wiese** [uber/h3#662]
The migration guide for updates from v3 to v4 is very helpful: https://h3geo.org/docs/library/migrating-3.x/

Unfortunately, the link (in the text, not the navigation) to the list of functions… behaves in an interesting way. It works under some circumstances, doesn't under others.

* When opening the link in a new tab (i.e. page loaded as full HTTP request) everything is fine
* When opening the link inside the documentation page, it tries to open https://h3geo.org/docs/library/migrating-3.x/migration-3.x/functions (mind migrati**ng**-3.x [the file] vs migrati**on**-3.x [the folder]) - which does not work..

I was going to create a PR but I don't really know what to propose as things look sane in the [source](https://github.com/uber/h3/blob/36cdd7679111911f14cf758335fc052ba627739d/website/docs/library/migrating-3.x.md?plain=1#L20). Maybe it's a bug in Docusaurus?

**Comment by isaacbrodsky** [comment]
I think this has to do with the file not matching up between slug / sidebar / location. I am able to fix it locally, although I don't see open as new tab as working.

**Comment by wiese** [comment]
Thanks for the effort (and thanks for catching that it actually affects all links on that page). However, this did not improve things on my end, just changed how it misbehaves. Now the links have a double library/library/ in their path. I suspect it's the JS on the page interfering on click, as the URLs are fine on link hover/new page open.

**Comment by isaacbrodsky** [comment]
Ah, ok. This might indeed be a docusaurus bug. Could you post your OS version, browser name and version, and any browser extensions you're using that might be relevant?

**Comment by wiese** [comment]
I'm happy to provide browser information if that helps. But as I'm able to reproduce this on 3 browsers across 2 platforms, I'm confident that the cause lies somewhere else.

What happens if you open the first link in the ticket description (taking you to https://h3geo.org/docs/library/migrating-3.x/) and click on the "function names have changed" link in the text?

**Comment by isaacbrodsky** [comment]
My mistake, there is some difference between the built site and the `yarn start` hosted development site. The links are working on the development version only.
