### ISSUE TITLE
Version 4.x cell stats documentation: edge length missing

### ISSUE THREAD

**Issue by holgerteichgraeber** [uber/h3#666]
The cell stats table is currently missing edge length, the section is marked by a TODO: https://h3geo.org/docs/core-library/restable 

Would you mind updating this page in the documentation with edge lengths? It must have disappeared with v4, and it used to be extremely helpful in quickly looking up and comparing different resolutions and making modeling decisions.

**Comment by ajfriend** [comment]
IIRC, those original edge length values may have actually been incorrect. We planned to update them, but never got around to it. Also, it wasn't clear that there was an efficient way to compute the exact average without enumerating all of them (unlike the cell area case), so the proposal was to compute exact values for a few resolutions and then extrapolate. Something like this: https://gist.github.com/ajfriend/200299f857ed22bf34bde4dfbc562100

I can maybe take a look at some point, but I think we'd also be more than happy if someone took this on and put up a PR with a source notebook :)
