### ISSUE TITLE
Error in testCellsToLinkedMultiPolygon/gridDiskResolutions?

### ISSUE THREAD

**Issue by grim7reaper** [uber/h3#704]
Since the test use a 2-disks, I think that `numHexes` should be 19 (instead of 7), and thus `countLinkedCoords` would be 30.

Or am I misunderstanding something?

**Comment by nrabinowitz** [comment]
That... is completely correct. We were only taking the first 7 cells in the `gridDisk` output, which only represent the 1-disk, not the 2-disk. So the test was still working, but we weren't actually testing the full 2-disk. Thanks for the report!
