### ISSUE TITLE
Does starlink use H3?

### ISSUE THREAD

**Issue by VLiu7** [uber/h3#717]
Hi, first of all thanks for providing such a great tool.

Recently starlink updated their map on their website (https://www.starlink.com/map), the hex shape in the map is very similar to H3, I compared the results of H3 with the map and found an amazing match, the following two pictures are the results of H3 (hex resolution=5) on the left and starlink map on the right.
![image](https://user-images.githubusercontent.com/38338565/196445476-174e35eb-54ef-438a-9d0e-45e6285673f3.png)
![image](https://user-images.githubusercontent.com/38338565/196445512-b2dcaab5-c044-428d-851e-c9ca7568750e.png)

At the same time, I see many visualization sites doing coverage analysis of starlink based on H3, such as this blog (https://mikepuchol.com/modeling-starlink-capacity-843b2387f501)

What do the authors think about this, is starlink really using H3, or just for visualization?
In the April’s  #598, @sahrk and @nrabinowitz  denied this, has your opinion changed so far?  

Thanks in advance!

**Comment by sahrk** [comment]
Good question! Note that in issue #598 @nrabinowitz pointed out that I was wrong in my overly-quick conclusion, so the jury's still out for me. But I'm not sure what specifically led @nrabinowitz to think it isn't H3.

**Comment by VLiu7** [comment]
Thank @sahrk very much for your reply. Maybe @puchol and @dfellis in issue #589 have any new thoughts on this?

**Comment by puchol** [comment]
Starlink does now use H3, size 5, replacing their proprietary hexagonal cell system, which I wasn't able to reverse-engineer. My assumption is they need increasing granularity, as the cells are actually used for satellite resource scheduling, not only as a UI for customers to see coverage. Thus, size 6, 7 would make sense to further divide user terminals and the customer base.

**Comment by VLiu7** [comment]
Thank @puchol very much for your reply! So the conclusion that starlink uses H3 is only based on the match between H3 and the starlink map, right? Is there any other information to confirm this?

**Comment by puchol** [comment]
Yes, I have checked dozens of cells all over the Earth and they all match. It would be shocking to find they have managed to reproduce H3 cells precisely, without using H3 to begin with ;-)

**Comment by sahrk** [comment]
> Yes, I have checked dozens of cells all over the Earth and they all match. It would be shocking to find they have managed to reproduce H3 cells precisely, without using H3 to begin with ;-)

Do you know when they made the change to H3? Assuming H3 works for a use case, it's hard to see why anyone would roll their own hexagonal DGGS.

**Comment by nrabinowitz** [comment]
> Good question! Note that in issue #598 @nrabinowitz pointed out that I was wrong in my overly-quick conclusion, so the jury's still out for me. But I'm not sure what specifically led @nrabinowitz to think it isn't H3.

At the time, both the size and the orientation of the cells on the coverage map didn't seem to match H3. The current Starlink availability map looks much more likely to be H3, so I've no reason to doubt @puchol though I haven't verified yet.

**Comment by VLiu7** [comment]
> > Good question! Note that in issue #598 @nrabinowitz pointed out that I was wrong in my overly-quick conclusion, so the jury's still out for me. But I'm not sure what specifically led @nrabinowitz to think it isn't H3.
> 
> At the time, both the size and the orientation of the cells on the coverage map didn't seem to match H3. The current Starlink availability map looks much more likely to be H3, so I've no reason to doubt @puchol though I haven't verified yet.

Thanks for the reply, I have a straightforward question. Do you have any insight why starlink has adopted H3? For LEO constellation, what are the advantages of H3 over S2, GeoHash and other tools? @puchol @nrabinowitz @sahrk

**Comment by puchol** [comment]
> > Yes, I have checked dozens of cells all over the Earth and they all match. It would be shocking to find they have managed to reproduce H3 cells precisely, without using H3 to begin with ;-)
> 
> Do you know when they made the change to H3? Assuming H3 works for a use case, it's hard to see why anyone would roll their own hexagonal DGGS.

The change was made around mid-August. Starlink is extremely vertically integrated, they make everything themselves, so they had someone create their own system. What they then realized is they didn't have a mechanism to resolve the cells into larger or smaller sizes, and decided to adopt H3 instead.

**Comment by dvanduzer** [comment]
this is the most interesting H3 thread i have seen so far, and my only
contribution is to s---post: LEO is similar to ELO, the Electric Light
Orchestra.

**Comment by puchol** [comment]
> > > Good question! Note that in issue #598 @nrabinowitz pointed out that I was wrong in my overly-quick conclusion, so the jury's still out for me. But I'm not sure what specifically led @nrabinowitz to think it isn't H3.
> > 
> > 
> > At the time, both the size and the orientation of the cells on the coverage map didn't seem to match H3. The current Starlink availability map looks much more likely to be H3, so I've no reason to doubt @puchol though I haven't verified yet.
> 
> Thanks for the reply, I have a straightforward question. Do you have any insight why starlink has adopted H3? For LEO constellation, what are the advantages of H3 over S2, GeoHash and other tools? @puchol @nrabinowitz @sahrk

They adopted H3 to be able to have smaller and larger cells. If you need to subdivide a size 5 H3 cell into smaller sub-cells, e.g. to assign different SLAs to each sub-area, you need to be able to change cell size, which their initial system didn't allow. As satellite spot beams are elliptical in shape, hexagonal cells are easier to circumscribe. S2, for example, uses parallelograms, onto which you cannot easily project an ellipse.

**Comment by dvanduzer** [comment]
wikipedia lists 7 non-hierarchical DGGs and 9 of the hierchy... arch... indexable telescoping grids?

ISEA is at the top and S2 is at the bottom of the second list. so if starlink tried to develop a proprietary system based on X arbitrary characteristic... how many of these 16+ systems could they definitely *not* be reverse engineering?

**Comment by VLiu7** [comment]
Thanks guys, I've learned a lot from this thread. I will close this issue.
