### ISSUE TITLE
Alternative implementation in Rust

### ISSUE THREAD

**Issue by grim7reaper** [uber/h3#744]
Hi,

I've just [published](https://old.reddit.com/r/rust/comments/1075bm1/ann_an_harder_better_faster_stronger_version_of/) a complete rewrite of H3 in Rust (on par with the 4.0 version).
It comes with some bells and whistles (such as GeoJSON support) and a few optimizations (resulting in 2-digit speedup in some cases).

Should I make a PR to add it to the doc page that list the bindings?
Or is it limited to bindings only?

**Comment by isaacbrodsky** [comment]
Hi -- this is very exciting to see. That page does include translations/ports (there's already a couple for C#), so happy to accept a PR to link to your translation to Rust.
