### ISSUE TITLE
X,Y,Z to Lat, Long ?

### ISSUE THREAD

**Issue by SkybuckFlying** [uber/h3#756]
What is the best way to do this ? My raytracer works with X,Y,Z. Uber works with Lat, Long as well as other libraries.

Uber does not have X,Y,Z to Lat, Long conversion routine ?!

Please add ?!?

**Comment by SkybuckFlying** [comment]
This document seems to work good:

GPS_Facts_XYZ-NED.pdf

At least I tried the ConvertECEFToLTP and it works good !

CU LATER.

**Comment by isaacbrodsky** [comment]
I don't think we intend to add x/y/z coordinate support to the library.
