### ISSUE TITLE
Is h3-c perfectly compatible with c plus plus?

### ISSUE THREAD

**Issue by GitBenjamin** [uber/h3#761]
I wanted to integrate H3 into my project to experiment, but I was worried that it wouldn't work well with cpp. @nrabinowitz @isaacbrodsky

**Comment by isaacbrodsky** [comment]
The C library itself should be compatible with C++. We already use `extern "C"` blocks for the exported functions (https://github.com/uber/h3/blob/master/src/h3lib/include/h3api.h.in#L62) and so the H3 header file should work as-is.

If you copy the H3 source code in and run it through a C++ compiler I would expect it will work. We are not depending on very modern versions of C. The results will depend on the specific C++ compiler you use and how it treats C source files. Please let us know if there's a compiler out there that can accept C but has issues with H3.

**Comment by GitBenjamin** [comment]
Thank you! I will try it.
