### ISSUE TITLE
Uber CLA Contact

### ISSUE THREAD

**Issue by KelseyBlodgett** [uber/h3#782]
Hello, 

I am with the Amazon OSPO and we have a CCLA signed with Uber so our employees can send back contributions. I have in my notes that we are supposed to contact Jim Jagielski when we want to add new contributors to the CCLA but I got a bounce back when I tried to email them. How should I add contributors to our CLA?
thanks!
Kelsey

**Comment by jonathanbaker7** [comment]
Hi Kelsey.  

Feel free to reach out to ospo@uber.com for any notifications.  I will also take a look at the Amazon CCLA and see if we can update it so that notifications are not required.  

Email me directly if you have any questions. jonbaker at uber.com.
