### ISSUE TITLE
Meta: blog post has broken images

### ISSUE THREAD

**Issue by danielhoherd** [uber/h3#835]
Apologies for posting this issue here, but I can't find anywhere else to report it. There is [a fantastic blog post intro to H3](https://www.uber.com/blog/h3/), and it has a bunch of broken images, and a bunch of broken hyperlinks on images. This blog post does not seem to appear anywhere else in the docs, and archives of it . It would be great if those broken images could be fixed because they play such a big part in illustrating what H3 does. [The oldest archive I can find for it](https://web.archive.org/web/20220816193857/https://www.uber.com/blog/h3/) also has broken images, so without restoring the images to the original blog post, that information will be lost forever.

**Comment by isaacbrodsky** [comment]
Thanks for the comment -- I'm raising this with my contacts at Uber.

**Comment by ajfriend** [comment]
I found the original google doc version of the blog post and am just waiting to hear back from the newsroom team to see if we can get those images uploaded and fixed.

**Comment by ajfriend** [comment]
Sounds like there is a fix going out around Wednesday, May 22, between 4:00 am to 6:00 am EST.

**Comment by isaacbrodsky** [comment]
It looks like this is fixed now!

**Comment by danielhoherd** [comment]
Awesome! Thank you all for handling that, and quickly!
