### ISSUE TITLE
Missing return statement from func declared as returning int.

### ISSUE THREAD

**Issue by sgbeal** [uber/h3#85]
https://github.com/uber/h3/blob/518b324f30549244d31fedc242a3a97dc59916af/examples/neighbors.c#L44

In my experience, only MS compilers won't complain about a missing return.

**Comment by sgbeal** [comment]
Same here:

https://github.com/uber/h3/blob/master/examples/edge.c#L39

**Comment by sgbeal** [comment]
And here:

https://github.com/uber/h3/blob/master/examples/index.c#L50

**Comment by isaacbrodsky** [comment]
Hi, I just checked using GCC 6 and do not see any errors or warnings. Looking this up online, it looks like the C99 standard permits not explicitly returning from `int main`. See for example: https://stackoverflow.com/questions/3727051/why-does-a-main-function-without-a-return-statement-return-value-12/3728153#3728153 Do you have an example compiler/version that's able to compile the example but warns or doesn't emit the return 0?

I don't think there'd be an objection to adding an explicit return statement if you'd like to open a PR.

**Comment by sgbeal** [comment]
i didn't attempt compilation - just eyeballed the code (and it failed that compilation check ;)). Adding an explicit return for a function declared as returning a value is simply The Right Thing To Do, main() or not.
