### ISSUE TITLE
Issue with H3: Uber’s Hexagonal Hierarchical Spatial Index

### ISSUE THREAD

**Issue by assistaditya** [uber/h3#851]
Currently, I am using the Uber H3 index library for my geospatial analysis. The version of the library is h3-3.7.7. If the version changes tomorrow, the corresponding H3 index for the given latitude and longitude might also change, affecting my entire dataset. How can I solve this issue?

**Comment by dfellis** [comment]
That's technically true but hasn't ever happened in the entire life of this library. While there have been major version changes, they are to the API of H3, not it's index. The index format is well-documented, and [makes note of various modes](https://h3geo.org/docs/core-library/h3Indexing). We have added new modes over time, but have never dropped old modes.

If we wanted to make a backwards-incompatible change to a given mode, which we are *loathe* to do, we would likely implement the change as a new mode and accept both the old and new modes for a significant time (eg, years), and would include a simple way to convert anything indexed in the old mode into the new mode.

But, again, this is *very* unlikely to happen, as it hasn't for the lifetime of the open source project (about 7 years now, I think?) and only happened once during the internal beta (mode 0, which is now used to indicate an invalid H3 index).

**Comment by assistaditya** [comment]
Thanks
