### ISSUE TITLE
make shapefiles available

### ISSUE THREAD

**Issue by rafapereirabr** [uber/h3#87]
One idea that might help spread the use of `h3` would be to make the shapefiles available on the github repo.

**Comment by cyivy1992** [comment]
+1 how can I generate the corresponding shapefiles?

**Comment by nrabinowitz** [comment]
Which shapefiles? There are 16 resolutions, and resolutions >= 5 have over a million hexagons (the count increases roughly by an order of magnitude at each resolution). Given this, I'm not sure what we could reasonably release in shapefiles - in general it would be best to generate only the portion of the grid you need.

I'm not an expert in shapefiles, but very roughly speaking you should be able to use `polyfill` to get the list of hexagons in your area of interest at a given resolution, then loop over them with `h3ToGeoBoundary` to get the coordinates. These could be output as WKT or GeoJSON and then passed to a util like `ogr2ogr` to convert to shapefiles.

**Comment by rafapereirabr** [comment]
Hi @nrabinowitz, I was referring to the 16 shapefiles, each corresponding to a resolution. I recognize the shapefiles would probably be too large, though. As you said, perhaps the best approach would be to use a set of functions that take an area of interest as an input and outputs the hexagonal grid for that area at a defined resolution. Perhaps that is something that could be done in the [`h3r` package in `R`](https://github.com/uber/h3) developed by @scottmmjackson (?)

**Comment by scottmmjackson** [comment]
It could be done. I owe that repo some TLC; locally I have more than half the other functions implemented and I've changed the method signatures but ultimately you could output the point polygons and export them to shapefiles.

**Comment by cyivy1992** [comment]
Hi @nrabinowitz, I am new to shapefile and I have never worked with WKT or GeoJSON before, so any instruction of how to get them is very helpful. Particularly, I'm interested in the bay area with resolutions =6,7 and 9. Any idea how I can the corresponding shapefiles?

**Comment by nrabinowitz** [comment]
@cyivy1992 - this is a question rather than a feature request or bug report, so can I ask you to post it on [StackOverflow](https://stackoverflow.com) with the [h3 tag](https://stackoverflow.com/questions/tagged/h3) instead, and I can try to answer it there? The answer depends in part on what language you want to use - this may be easier using the JS or Java bindings than using the C lib directly.

**Comment by cyivy1992** [comment]
Just did: https://stackoverflow.com/questions/51159241/how-to-generate-shapefiles-for-hexagons
Thanks a lot! @nrabinowitz

**Comment by isaacbrodsky** [comment]
Closing in favor of StackOverflow

**Comment by justinelliotmeyers** [comment]
Does anyone have a full global hex dataset for these? Thanks!!
