### ISSUE TITLE
Mapbox basemap not loading on new home page

### ISSUE THREAD

**Issue by bnaul** [uber/h3#893]
@isaacbrodsky's resdesigned home page from #836 is very slick, but it appears to be hitting some Mapbox credentials issue:
<img width="282" alt="image" src="https://github.com/user-attachments/assets/13a7a3fb-4871-4dab-ab1d-3568cdaddfab">
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/545219c2-2397-4fa5-924d-3e7d7b9abaa0">

I confirmed that the token itself is the issue by swapping the token `pk.eyJ1IjoidWJlcmRhd...` from the request for my own public token, which works fine.

**Comment by isaacbrodsky** [comment]
We're aware and working on fixing the token

**Comment by bnaul** [comment]
Seems to be fixed!
