### ISSUE TITLE
h3geo.org Python documentation appears incorrect for 4.1.1

### ISSUE THREAD

**Issue by rohanaras** [uber/h3#942]
The documentation for few of the h3 4.x geometry related functions appear to be incorrect at [https://h3geo.org/docs/api/misc/](https://h3geo.org/docs/api/misc/). After reading through a few of the other issues here, I realized that I should be using the [Python specific documentation](https://uber.github.io/h3-py/intro.html), which appear correct. Regardless, this is something that is confusing and should be fixed imo.

Here is a list of the differences I noticed, though this could be incomplete:
-  [`get_hexagon_edge_length_avg`](https://h3geo.org/docs/api/misc/#gethexagonedgelengthavgkm) vs [`average_hexagon_edge_length`](https://uber.github.io/h3-py/api_verbose.html#h3.average_hexagon_edge_length)
- [`exact_edge_length`](https://h3geo.org/docs/api/misc/#edgelengthkm) vs [`edge_length`](https://uber.github.io/h3-py/api_verbose.html#h3.edge_length)
- [`get_hexagon_area_avg`](https://h3geo.org/docs/api/misc/#gethexagonareaavgkm2) vs [`average_hexagon_area`](https://uber.github.io/h3-py/api_verbose.html#h3.average_hexagon_area)

**Comment by ajfriend** [comment]
You're totally right. Thanks for spotting!

If you wanted to take a stab at updating the h3geo.org docs, that would definitely be appreciated. And it shouldn't be too hard to update / we'd be happy to answer any questions.  

Otherwise, I'll try to update the doc myself soon.
